### ISSUE TITLE
Windows 10 ビルド 17730 で NVDA を更新するとエラーが出る

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#100]
Windows 10 Insider ビルド 17730 （32ビット）で 
NVDA 日本語版 2018.2.1jp から jpalpha 180706n への上書き、
さらに 180806n への更新を行っていますが、
インストールの最後に「更新は失敗しました」と表示されます。
ですが NVDA を再起動すると新しいバージョンが動いています。

エラーの内容から判断すると、
スタートメニューにフォルダを作成する権限がないようです。

NVDAメニューからヘルプを開くと最新のドキュメントが閲覧できています。

```
ERROR - RPC process 8096 (nvda_slave.exe) (10:05:37.874):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 42, in main
  File "installer.pyo", line 431, in install
  File "installer.pyo", line 251, in registerInstallation
  File "installer.pyo", line 46, in createShortcut
  File "os.pyo", line 157, in makedirs
WindowsError: [Error 5] アクセスが拒否されました。: u'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\NVDA\\説明'
ERROR - gui.installerGui.doInstall (10:05:37.903):
Installation failed: 1
```

**Comment by nishimotz** [comment]
現在は起きておらず、その時点での Windows 10 Insider 環境の問題かも知れません。
様子を見ます。
