### ISSUE TITLE
appveyor ビルドの ImportError 

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#103]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/build/alphajp-734

テストの最後のほうでエラーになっている。

```
jptools\tests.cmd
0 errors, 0 unexpected successes, 76 expected errors
Traceback (most recent call last):
  File "jpDicTest.py", line 17, in <module>
    import jpUtils
  File "..\source\jpUtils.py", line 9, in <module>
    import config
  File "..\source\config\__init__.py", line 28, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj
Collecting artifacts...
Found artifact 'jptools\nvdajp-jtalk-180904q.nvda-addon' matching 'jptools\nvdajp-jtalk-*.nvda-addon' path
Found artifact 'jptools\__jpdictest_log.txt' matching 'jptools\__jpdictest_log.txt' path
Found artifact 'output\nvda_jpalpha_180904q.exe' matching 'output\*' path
Found artifact 'output\nvda_jpalpha_180904q.pot' matching 'output\*' path
Found artifact 'output\nvda_jpalpha_180904q_controllerClient.zip' matching 'output\*' path
Found artifact 'output\nvda_jpalpha_180904q_controllerClientJp.zip' matching 'output\*' path
Found artifact 'output\nvda_jpalpha_180904q_verify.log' matching 'output\*' path
No artifacts found matching 'output\*\*' path
No artifacts found matching 'miscDepsJp\jptools\__h1output.txt' path
No artifacts found matching 'miscDepsJp\jptools\__h2output.txt' path
No artifacts found matching 'miscDepsJp\jptools\__test_log.txt' path
Uploading artifacts...
[1/7] jptools\nvdajp-jtalk-180904q.nvda-addon (20,633,019 bytes)...100%
[3/7] output\nvda_jpalpha_180904q.exe (38,741,200 bytes)...100%
[4/7] output\nvda_jpalpha_180904q.pot (414,305 bytes)...100%
[5/7] output\nvda_jpalpha_180904q_controllerClient.zip (2,087,019 bytes)...100%
[6/7] output\nvda_jpalpha_180904q_controllerClientJp.zip (2,033,095 bytes)...100%
[7/7] output\nvda_jpalpha_180904q_verify.log (6,422 bytes)...100%
Build success
```

**Comment by nishimotz** [comment]
実害はないが未解決
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/21232005
