### ISSUE TITLE
NVDA日本語アルファ版の更新がエラーになる

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#174]
日本語アルファ版の更新処理がいつの間にか止まっていて、
ログを確認すると下記のエラーが出ている。

190205 あたりからという話。

```
ERROR - unhandled exception (16:59:19.372):
Traceback (most recent call last):
  File "updateCheck.pyo", line 734, in onClose
  File "updateCheck.pyo", line 418, in _download
  File "updateCheck.pyo", line 554, in __init__
KeyError: 'apiVersion'
```

**Comment by nishimotz** [comment]
NVDA側の仕様変更にあわせてサーバー側の更新を行っています。
現在の日本語アルファ版は 190219k です。

**Comment by nishimotz** [comment]
日本語アルファ版、問題なく 190219s （あるいは、これより新しいもの）に更新されるはずです。
サーバーが通知するべき情報は appveyor-jp.yml  で出力しています。
