### ISSUE TITLE
マルチバイト文字が含まれる実行ファイルを起動すると操作できない

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#198]
### 問題の再現手順

1. 実行ファイルのファイル名にマルチバイト文字が含まれるプログラムを起動する。
　※ 例として、簡単なアプリケーションを添付しています。
　これ以外のファイルでも発生することを確認しています。
2. ログにエラーが出力され、アプリケーションを操作することができない。

### 期待されること

　添付しているアプリケーションの例だと、Tabキーを押して、エディットボックスやボタンにフォーカスされる

### 実際に起きること

　起動すると、ログに下記のエラーが出力される。

    ERROR - core.CorePump.run (22:31:28.094):
    errors in this core pump cycle
    Traceback (most recent call last):
      File "core.pyo", line 496, in run
      File "IAccessibleHandler.pyo", line 903, in pumpAll
      File "IAccessibleHandler.pyo", line 614, in processGenericWinEvent
      File "appModuleHandler.pyo", line 137, in update
      File "appModuleHandler.pyo", line 123, in getAppModuleFromProcessID
      File "appModuleHandler.pyo", line 174, in fetchAppModule
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)
    ERROR - queueHandler.flushQueue (22:31:28.124):
    Error in func update from eventQueue
    Traceback (most recent call last):
      File "queueHandler.pyo", line 53, in flushQueue
      File "appModuleHandler.pyo", line 137, in update
      File "appModuleHandler.pyo", line 123, in getAppModuleFromProcessID
      File "appModuleHandler.pyo", line 174, in fetchAppModule
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)
    ERROR - core.CorePump.run (22:31:28.144):
    errors in this core pump cycle
    Traceback (most recent call last):
      File "core.pyo", line 496, in run
      File "IAccessibleHandler.pyo", line 889, in pumpAll
      File "IAccessibleHandler.pyo", line 651, in processFocusWinEvent
      File "appModuleHandler.pyo", line 137, in update
      File "appModuleHandler.pyo", line 123, in getAppModuleFromProcessID
      File "appModuleHandler.pyo", line 174, in fetchAppModule
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)
    ERROR - core.CorePump.run (22:31:28.203):
    errors in this core pump cycle
    Traceback (most recent call last):
      File "core.pyo", line 496, in run
      File "IAccessibleHandler.pyo", line 903, in pumpAll
      File "IAccessibleHandler.pyo", line 614, in processGenericWinEvent
      File "appModuleHandler.pyo", line 137, in update
      File "appModuleHandler.pyo", line 123, in getAppModuleFromProcessID
      File "appModuleHandler.pyo", line 174, in fetchAppModule
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)
    ERROR - core.CorePump.run (22:31:29.545):
    errors in this core pump cycle
    Traceback (most recent call last):
      File "core.pyo", line 496, in run
      File "IAccessibleHandler.pyo", line 903, in pumpAll
      File "IAccessibleHandler.pyo", line 614, in processGenericWinEvent
      File "appModuleHandler.pyo", line 137, in update
      File "appModuleHandler.pyo", line 123, in getAppModuleFromProcessID
      File "appModuleHandler.pyo", line 174, in fetchAppModule
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)

### システム構成

- NVDA 日本語版 jpalpha_190515u インストール環境
- Windows 10 バージョン 1809 日本語環境

### その他の質問

- PC を再起動してもこの問題は再発する：はい

### 他のバージョンの NVDA と比較している場合はその結果

　NVDA 2019.1.1 日本語版では正常に操作できることを確認しています。

[test_app.zip](https://github.com/nvdajp/nvdajp/files/3191689/test_app.zip)

**Comment by nishimotz** [comment]
ありがとうございます。
本家 alpha スナップショットで再現できるので、
本家にフィードバックするつもりです。

https://www.nvaccess.org/files/nvda/snapshots/

**Comment by nishimotz** [comment]
本家 alpha で問題が出ていない

nvda_snapshot_alpha-17104,6d4b1121.exe

ここから問題が起きる

nvda_snapshot_alpha-17134,363af94b.exe

というところまで確認しました。
すみませんが、本家に報告を書くときに「テストアプリケーション.exe」をお借りします。

**Comment by riku22** [comment]
検証ありがとうございます。

> すみませんが、本家に報告を書くときに「テストアプリケーション.exe」をお借りします。

　了解しました。
　たぶん大丈夫だとは思いますが、そもそも英語環境だとうまく起動できないとかがあるかもしれません。

**Comment by riku22** [comment]
検証ありがとうございます。

> すみませんが、本家に報告を書くときに「テストアプリケーション.exe」をお借りします。

　了解しました。

**Comment by nishimotz** [comment]
ちょうど別の問題とぶつかって、確認が遅くなりました。

jpalpha_190520j で修正できていると思うので、ご確認いただければ助かります。

**Comment by nishimotz** [comment]
本家版へのパッチでも問題は解決しているので、
本件は本家へのプルリクエストがマージされるまでオープンにしておきます。

**Comment by riku22** [comment]
ありがとうございます。
　ですが、Ctrl+NVDA+F1で「現在起動中のアプリのファイル名を読み込まれているアプリモジュールの名前とともに読み上げ」を実行すると、ログに下記のエラーが出ているようです。
　こちらだけでしょうか。

    ERROR - scriptHandler.executeScript (20:53:28.555):
    error executing script: <bound method GlobalCommands.script_reportAppModuleInfo of <globalCommands.GlobalCommands object at 0x04955450>> with gesture u'コントロール+NVDA+f1'
    Traceback (most recent call last):
      File "scriptHandler.pyo", line 192, in executeScript
      File "globalCommands.pyo", line 1700, in script_reportAppModuleInfo
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)

**Comment by nishimotz** [comment]
jpalpha_190521n にて Ctrl+NVDA+F1 の動作をご確認ください。

本家版ではもっとよい修正方法を提案したいのですが、
レビューに時間がかかるかも知れません。
本件で不具合が再発していたら、
お手数ですが、また教えていただけると助かります。

**Comment by riku22** [comment]
ありがとうございます。
　jpalpha_190521nで正常に報告されることを確認しました。

**Comment by nishimotz** [comment]
原因になった変更が本家版から取り除かれたので、クローズします。
