### ISSUE TITLE
KGS 点字ドライバーの改善

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#217]
タスク

* Python 3 対応
* nvda-japanese-users:2629 からの議論「スタートメニューの報告が不安定」問題の調査と対策
* 本家版に対するアドオンと、NVDA 日本語版に組み込むドライバーの両方を検討

**Comment by nishimotz** [comment]
いただいたエラー報告

```
INFO - core.main (11:13:11.767):
NVDA version jpalpha_190816w
INFO - core.main (11:13:11.767):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (11:13:11.767):
Using Python version 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]

INFO - core.main (11:13:12.797):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
DEBUG - core.main (11:13:12.797):
Initializing braille input
INFO - brailleInput.initialize (11:13:12.797):
Braille input initialized
DEBUG - core.main (11:13:12.797):
Initializing braille
INFO - braille.initialize (11:13:12.797):
Using liblouis version 3.9.0
INFO - braille.initialize (11:13:12.807):
Using pySerial version 3.4
INFO - brailleDisplayDrivers.kgs.BrailleDisplayDriver.__init__ (11:13:12.817):
first connection COM34
ERROR - braille.BrailleHandler.setDisplayByName (11:13:12.817):
Error initializing display driver kgs for kwargs {'port': 'COM34'}
Traceback (most recent call last):
  File "braille.pyc", line 1795, in setDisplayByName
  File "brailleDisplayDrivers\kgs.pyc", line 373, in __init__
  File "ctypes\__init__.pyc", line 442, in LoadLibrary
  File "ctypes\__init__.pyc", line 364, in __init__
OSError: [WinError 126] 指定されたモジュールが見つかりません。
INFO - braille.BrailleHandler.setDisplayByName (11:13:12.817):
Loaded braille display driver noBraille, current display has 0 cells.
```

**Comment by nishimotz** [comment]
下記アドオン版の KGS ドライバーをインストールすれば動くことを確認。
DLLの path 指定の不具合と思われる。

https://ci.appveyor.com/api/buildjobs/rq52rmr28xfqlnjq/artifacts/jptools%2Fkgsbraille-190816w.nvda-addon

**Comment by nishimotz** [comment]
AppVeyor のビルドログに下記の行があるはずなのだが、見つからなくなった。
もしかすると scons の設定で DLL を追加できていないのかもしれない。

```
copying brailleDisplayDrivers\DirectBM.dll -> C:\projects\nvdajp\dist\brailleDisplayDrivers
```

**Comment by nishimotz** [comment]
ログ出力を追加して確認したら、下記を読み込もうとして失敗していることが分かった

```
DEBUG - brailleDisplayDrivers.kgs.BrailleDisplayDriver.__init__ (21:27:40.662):
C:\Program Files (x86)\NVDA\library.zip\brailleDisplayDrivers\DirectBM.dll
```

**Comment by nishimotz** [comment]
jpalpha_190819v にて LoadLibrary エラーの対策を行いました。
py2exe の挙動が Python 2.7 のときと違うのかも知れません。

**Comment by nishimotz** [comment]
解決していないという報告

```
INFO - core.main (08:58:39.102):
NVDA version jpalpha_190819v
INFO - core.main (08:58:39.102):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (08:58:39.102):
Using Python version 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
INFO - core.main (08:58:39.102):
Using comtypes version 1.1.7
INFO - core.main (08:58:39.102):
Using configobj version 5.1.0 with validate version 1.0.1

DEBUG - brailleDisplayDrivers.kgs.BrailleDisplayDriver.__init__ (08:58:49.139):
C:\Program Files\NVDA\library.zip\brailleDisplayDrivers\DirectBM.dll
ERROR - braille.BrailleHandler.setDisplayByName (08:58:49.139):
Error initializing display driver kgs for kwargs {'port': 'COM34'}
Traceback (most recent call last):
  File "braille.pyc", line 1795, in setDisplayByName
  File "brailleDisplayDrivers\kgs.pyc", line 374, in __init__
  File "ctypes\__init__.pyc", line 442, in LoadLibrary
  File "ctypes\__init__.pyc", line 364, in __init__
OSError: [WinError 126] 指定されたモジュールが見つかりません。
```

**Comment by nishimotz** [comment]
私の2台の Windows 10 PC で jpalpha_190819v をインストール実行し、
1台では期待通りに動作し、
もう1台は報告されたエラーを再現しています。
いずれもアドオンを無効化して確認しています。
なぜこうなるのか。。

**Comment by nishimotz** [comment]
どうやら私がビルド 1105 と 1106 の2種類の  jpalpha_190819v を作ってしまい、
1106 ではなく 1105 を配信してしまったようです。
新しいタイムスタンプで配信をやり直します。

**Comment by nishimotz** [comment]
日本語アルファ版を jpalpha_190820k に更新しました。

**Comment by nishimotz** [comment]
現状のビルドで作られた KGS アドオンは、
たぶん本家版 NVDA でうまく動かないので、
もういちど書き直す必要あり。

**Comment by nishimotz** [comment]
* 現在 AppVeyor でビルドしている kgsbraille アドオンは DirectBM.dll のパス指定が間違っていて本家版 NVDA で動作しない
* 最近の機種では read ボタンではなく「ウィンキー」とよばれている
* 自動接続がうまく動いていない

**Comment by nishimotz** [comment]
自動接続、bdDetect.py に情報を追加して、さらに _getTryPorts() を使うようにドライバーを変更する必要がありそう。

**Comment by nishimotz** [comment]
2022.1jp で予定する改善

* kgs ドライバーで自動接続できなかった問題を修正
* NVDA 日本語版と同時にビルドする kgsbraille アドオンが NVDA 本家版で動作しなかった不具合を修正
* kgsbraille アドオンが対応する NVDA は 2019.3 から 2022.1 まで、それぞれの本家版と日本語版

**Comment by mitsugusakamoto** [comment]
readきーはbm24/bm46/bn46x/bmpkまでです。
BM32とBMスマート16/40、BMスマートエア16/32はウィンキーと呼ぶようにしました。

**Comment by mitsugusakamoto** [comment]
NVDA アルファ版ですが、KGS点字ディスプレイドライバでブルートゥースのポートも自動検出するようになってから、点字ディスプレイの電源が入っていない時にNVDAが動き始めると自動検出が無限ループするような気がします。まだ再現させる手順ははっきりしませんが、ポートの自動検出が無限ループすることは確認しています。

**Comment by nishimotz** [comment]
新しいチケット #334 を作ったので、そちらで議論させてください。
