### ISSUE TITLE
nvdajp 独自コードの Python3 / speech refactor 対応

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#219]
方針案

* JTalk と KGS ドライバーがアドオンとして本家 Python 3 版 NVDA で動作（ほぼ完了）
* それ以外の nvdajp 独自コードを Python 2/3 両対応コードにしつつ日本語アルファ版を更新
* 本家 master をマージ（本家による Python 3 移行作業がマージされて Python 3 版 NVDA 日本語版になる）
* Python 2 対応を捨てて Python 3 のみ対応のコードにする

**Comment by nishimotz** [comment]
speech refactor 対応は単純にできそうにない。

現在 py37jp ブランチは speech モジュールの独自コードをすべて取り除いている。

NVDA 日本語版で、過去に何をやってきたかいったん整理する。

## チケット

英語環境で使う場合の文字説明の処理
https://osdn.net/projects/nvdajp/ticket/35037
#2 

Vocalizer for NVDA レビューカーソル移動の読み上げ
#73 

「2回押すとスペルを読み上げる」機能の日本語対応
https://osdn.net/projects/nvdajp/ticket/34977

「すべて読み上げ」で改行をまたぐ単語を適切に読み上げない
https://osdn.net/projects/nvdajp/ticket/33823

サロゲートペアへの対応
https://osdn.net/projects/nvdajp/ticket/30841

「レビュー内の現在の文字を通知」2回押しの場合だけかな文字とアルファベットのフォネティック読みを
https://osdn.net/projects/nvdajp/ticket/34812

音声エンジンが英語の場合に「アルファベットをフォネティック読みする」の設定が反映されない
https://osdn.net/projects/nvdajp/ticket/34141

「文字を通知」コマンド仕様の再検討と点字ディスプレイ対応
https://osdn.net/projects/nvdajp/ticket/31467

## NVDA日本語版の説明

http://www.nvda.jp/nvda2019.1.1jp/ja/readmejp.html

4.1 文字報告モード
5.1.4. 半角全角キーが押されたらビープ音を鳴らす
5.1.5. かな文字をフォネティック読み
5.1.6. アルファベットをフォネティック読み
5.1.7. カタカナの声の高さの変化(-100から100)
5.1.8. 半角の声の高さの変化(-100から100)
5.2.3. スペル読み機能
8.2. スピーチビューアーと点字ビューアー

**Comment by nishimotz** [comment]
py37jp ブランチ
* unittest が通らないので braille.py も本家版 master と同じ状態に戻してみる

**Comment by nishimotz** [comment]
テストが通って artifacts がちゃんと実行できることを確認したので、
本家版に戻した braille と speech の各モジュールの再修正に取り掛かる。

**Comment by nishimotz** [comment]
ブランチ py37jp

ローカルの Python 3.7.4 32bit 環境で
```
python -m nose -sv ./tests/unit
```
が通るように braille 関連の修正を行った。

**Comment by nishimotz** [comment]
現状
https://github.com/nvdajp/nvdajp/commit/f935a05034b08e9f2e20b34ea66fc5cafc5ca7e6

* NVDA+ピリオド3回で16進数をそれらしく読む変更は動いている
* 点字ビューアーは移植したつもりだが動いていない（開くと読み上げが止まる）
* NVDA+A で改行をまたぐ日本語の読み上げの改良は移植したつもりだが動いていない

例えば下記の例で
「かんれんのしゅうせいをおこなった」ではなく
「かんれんのおさむ、せいをおこなった」と読まれる

```
関連の修
正を行った。
```

**Comment by nishimotz** [comment]
メモ

NVDA+ピリオド3回

```
IO - inputCore.InputManager.executeGesture (23:12:12.985):
Input: kb(laptop):NVDA+.
IO - speech.speak (23:12:13.025):
Speaking [LangChangeCommand ('ja'), 'タダシイノ セイ', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (23:12:13.246):
Input: kb(laptop):NVDA+.
ERROR - scriptHandler.executeScript (23:12:13.285):
error executing script: <bound method GlobalCommands.script_review_currentCharacter of <globalCommands.GlobalCommands object at 0x0BC45850>> with gesture 'NVDA+.'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 190, in executeScript
  File "globalCommands.pyc", line 1176, in script_review_currentCharacter
TypeError: spellTextInfo() got an unexpected keyword argument 'useDetails'
IO - inputCore.InputManager.executeGesture (23:12:13.567):
Input: kb(laptop):NVDA+.
IO - speech.speak (23:12:13.589):
Speaking [LangChangeCommand ('ja'), '27491 u+ロクビーロクサン']
```

NVDA+A

```
IO - inputCore.InputManager.executeGesture (23:12:36.266):
Input: kb(laptop):NVDA+a
IO - speech.speak (23:12:36.285):
Speaking [<speech.commands.CallbackCommand object at 0x0FC032F0>, LangChangeCommand ('ja'), '関連の修\n', <speech.commands.CallbackCommand object at 0x0FC03370>, '正を行った。']
IO - speech.speak (23:12:37.879):
Speaking [<speech.commands.CallbackCommand object at 0x0EAC5EB0>]
```

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26447704/artifacts

* NVDA+A で改行をまたぐ日本語の読み上げの改良が動作した

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26466528/artifacts
* 点字ビューアーが動作

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26467292/artifacts

* 文字説明モードが動作していない
* 半角の声の高さの変化は NVDA+ピリオド 2回のときには動作する
* JTalk と SAPI4 でピッチ変更コマンドが動かない（後者は本家版の仕様？）

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26472366/artifacts

* 文字説明モードはまだ動作していない
* JTalk で半角の声の高さ、カタカナの声の高さの動作を確認

```
カタカナ
ｶﾀｶﾅ
ABCabc
```

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26492222/artifacts

文字説明モード

* 従来のパッチは、レビューカーソルの移動では動いていた
* editableText に新たに手を加えて、（メモ帳のテキスト編集など）キャレット移動が文字説明モードに対応するように修正した。いちど出力した音声をキャンセルして文字説明を読み直しているので、音声エンジンの処理速度によって正しく動かない可能性はある。
* 全体として、だいたい 2019.2jp ベータと同様の動作になった
* 文字の種類でピッチを変える処理については、 SAPI4 では以前のバージョンでも動いておらず、ここのブランチでも動いていない。

**Comment by nishimotz** [comment]
現状の editableText ハックの問題点
* 行の右から左矢印キーでキャレット移動して、左端にくると（キャレットが動かないので）左矢印キーを押したときに説明読みしない

**Comment by nishimotz** [comment]
py37jp ブランチ

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26582531/artifacts

* 1行目の左端で左矢印キーを押した場合も説明読みを行う
* editableText で出力をキャンセルせずに切り替える方法で再実装。音声エンジンとの互換性の問題が起こりにくくなったはず

**Comment by nishimotz** [comment]
py37jp ブランチを alphajp にマージしました。

**Comment by nishimotz** [comment]
Google Chrome のブラウズモードで、左右矢印キーを押したとき、
以前のバージョンでは説明モードの読み上げをしていたが、
現在の alphajp では読み方モードの読み上げになっている。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/26712474/artifacts

**Comment by nishimotz** [comment]
文字説明モードを speakTextInfo で処理するように再修正

**Comment by nishimotz** [comment]
期待通りの動作になったので jpalpha_190815s を配信開始しました。

**Comment by nishimotz** [comment]
次のベータ版でいったん sayAll の処理をキャンセルして本家版の挙動に戻す。

2019.2jp までの実装の再利用をやめて、
* まず re_last_pause の正規表現をちゃんと日本語に対応させる、
* 次に全角文字の単語が複数の出力コマンドに分離する場合の処理を修正する
という方針で検討する。

**Comment by nishimotz** [comment]
speech モジュールの sayAll 処理にに関するテストコード

```
import re

re_last_pause = re.compile(r"^(.*(?<=[^\s.!?])[.!?][\"'”’)]?(?:\s+|$))(.*$)",re.DOTALL|re.UNICODE)
re_last_pause_ja = re.compile(r"^(.*(?<=[^\s.!?。、])[.!?。、][\"'”’)]?(?:\s+|$)?)(.*$)",re.DOTALL|re.UNICODE)

def check_before_after(item):
    m=re_last_pause_ja.match(item)
    if m:
        before,after=m.groups()
        print("before: " + before)
        print("after: " + after)
    else:
        print('** do not match **')

check_before_after("hello. world")
# before: hello. 
# after: world

check_before_after("hello。world")
# before: hello。
# after: world

check_before_after("NVDAは。そう、コミュニティーの援")
# before: NVDAは。そう、
# after: コミュニティーの援

check_before_after("あいうえお")
# ** do not match **

check_before_after("あいうえお。")
# before: あいうえお。
# after: 
```

メモ
* オリジナルの re_last_pause は before にマッチするためにピリオドやカンマの直後に空白が必要
* 日本語の句読点では直後の空白が不要なので (?:\s+|$)? の最後の ? を追加している

**Comment by nishimotz** [comment]
残念ながら新しい実装でも OneCore で「すべて読み上げ」が途中で止まる現象が起きる。
あまり時間をかけられないので、「すべて読み上げ」の日本語対応を
デフォルトで無効化して、ユーザーが設定で有効化できるようにする、
という仕様案を検討します。

**Comment by nishimotz** [comment]
re_last_pause は日本語の句読点対応をせず本家版と同じ処理をして、
jpUtils.filterSpeechSequenceForSayAll で
「漢字とカタカナの複数文字の行またぎだけ修正」
をしてみたところ OneCore で期待通りに下記をすべて読み上げるようになった。

```
NVDAは、コミュニティーの援
助によりNV Accessが開発しました。

この番組は
ざくろの森音楽研究所制作、
オカテツ電子研究所の提供でお送りしました。
来週はゲストをお迎えしての生放送です。

お便りはEメールまたはお葉書でお送りください。
皆様からのお便りお待ちしています。
```

デフォルト無効化ではなく、この実装で進めたいと思います。

**Comment by nishimotz** [comment]
このパターンで変な問題が起きた

```
IO - speech.speak (11:35:47.183) - MainThread (21616):
before filterSpeechSequenceForSayAll [LangChangeCommand ('ja_JP'), 'エディット', '読み取り専用', '複数行']
IO - speech.speak (11:35:47.183) - MainThread (21616):
Speaking [LangChangeCommand ('ja_JP'), 'エディット読', 'み取り専用複数', '行']
```

**Comment by nishimotz** [comment]
従来の「すべて読み上げ」の日本語対応

https://osdn.net/projects/nvdajp/ticket/33823

の処理は、副作用のほうが大きく、
2019.3 への移行というこの機会に方針を変更して、
今後は実装しない、に気持ちが傾いています。

今回の #247 の報告でわかったのですが、
音声エンジンによって speechRefactor への対応状況の詳細が異なり、
以前よりも、想定外の挙動が起きる可能性が高くなりました。

また、これは以前からの課題ですが、
以下のようなケースを正しく判断するのは
文字コード処理では無理があります。

```
処理が必要ないケース

読み取り専用
複数行
```

```
処理が必要なケース

NVDAは、コミュニティーの援
助によりNV Accessが開発しました。
```

**Comment by nishimotz** [comment]
2019.3jp では追加の作業は見送って #249 で続きを検討します。
