### ISSUE TITLE
ATOK 候補コメント対応

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#227]
最近のバージョンで ATOK 候補コメントの処理が動いていないようなので、
調査中です。

ドキュメントに書いた仕様
http://www.nvda.jp/nvda2019.2jp/ja/readmejp.html#toc53

過去の作業
#1
#14

**Comment by nishimotz** [comment]
* NVDA 2018.3.2jp + ATOK 2019 : 動作する
* NVDA 2018.4.1jp + ATOK 2019 : 動作する
* NVDA 2019.1.1jp + ATOK 2019 : 動作する
* NVDA 2019.2jp + ATOK 2019 : 動作する
* NVDA jpalpha 190910l + ATOK 2019 : 動作しない

2019.2jp まで動作しているようなので、 2019.3 系でのリグレッションではないか。

なお、190910l はまだ配信していません。

**Comment by nishimotz** [comment]
もうすこし調べました

* NVDA jpalpha 190729m (Python2) + ATOK 2019 : 動作する
* NVDA jpalpha 190815s (Python3) + ATOK 2019 : 動作しない

例えば #219 が関係ありそうです。

**Comment by nishimotz** [comment]
よく見たら import エラーだった

```
ERROR - core.CorePump.run (13:35:17.973):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 511, in run
  File "IAccessibleHandler.pyc", line 902, in pumpAll
  File "IAccessibleHandler.pyc", line 771, in processShowWinEvent
  File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 84, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 485, in findOverlayClasses
ModuleNotFoundError: No module named 'atok'
```

**Comment by nishimotz** [comment]
jpalpha_190911n でいままで通り動作するはずです。

**Comment by nishimotz** [comment]
マウスポインタの移動処理の不具合が残っているようです

```
ERROR - eventHandler.executeEvent (08:14:52.569):
error executing event: show on <NVDAObjects.IAccessible.atok.ATOKxxUIComment object at 0x0A62A170> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\atok.pyc", line 31, in event_show
  File "winUser.pyc", line 514, in setCursorPos
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1
ERROR - eventHandler.executeEvent (08:14:52.804):
error executing event: show on <NVDAObjects.IAccessible.atok.ATOKxxUIComment object at 0x0A62A170> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\atok.pyc", line 31, in event_show
  File "winUser.pyc", line 514, in setCursorPos
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1
```

**Comment by nishimotz** [comment]
jpalpha_190912k に更新しました。
