### ISSUE TITLE
JTalk で言語自動切換えの不具合

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#234]
jpalpha_191106q

lang 属性がある Web コンテンツで eSpeak との切り替えがうまくいっていない

```
INFO - __main__ (14:44:44.322) - MainThread (2404):
Starting NVDA version jpalpha_191106q
INFO - core.main (14:44:44.624) - MainThread (2404):
Config dir: C:\Users\nishimotz\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (14:44:44.624) - MainThread (2404):
Loading config: C:\Users\nishimotz\AppData\Roaming\nvda\nvda.ini
INFO - core.main (14:44:44.728) - MainThread (2404):
Using Windows version 10.0.18362 workstation
INFO - core.main (14:44:44.728) - MainThread (2404):
Using Python version 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
INFO - core.main (14:44:44.728) - MainThread (2404):
Using comtypes version 1.1.7
INFO - core.main (14:44:44.729) - MainThread (2404):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (14:44:45.384) - MainThread (2404):
Loaded synthDriver kctalker
INFO - core.main (14:44:45.531) - MainThread (2404):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (14:44:45.534) - MainThread (2404):
Braille input initialized
INFO - braille.initialize (14:44:45.534) - MainThread (2404):
Using liblouis version 3.10.0
INFO - braille.initialize (14:44:45.537) - MainThread (2404):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (14:44:45.542) - MainThread (2404):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (14:44:45.762) - MainThread (2404):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:44:45.772) - _UIAHandler.UIAHandler.MTAThread (10284):
UIAutomation: IUIAutomation6
INFO - core.main (14:44:46.041) - MainThread (2404):
NVDA initialized
INFO - synthDriverHandler.setSynth (14:44:53.191) - MainThread (2404):
Loaded synthDriver nvdajp_jtalk
ERROR - synthDrivers.jtalk._bgthread.BgThread.run (14:44:57.647) - Thread-7 (1744):
Error running function from queue
Traceback (most recent call last):
  File "synthDrivers\jtalk\_bgthread.pyc", line 38, in run
  File "synthDrivers\jtalk\jtalkDriver.pyc", line 208, in _speak
  File "synthDrivers\jtalk\jtalkDriver.pyc", line 185, in _espeak_speak
NameError: name 'unicode' is not defined
ERROR - synthDrivers.jtalk._bgthread.BgThread.run (14:44:58.984) - Thread-7 (1744):
Error running function from queue
Traceback (most recent call last):
  File "synthDrivers\jtalk\_bgthread.pyc", line 38, in run
  File "synthDrivers\jtalk\jtalkDriver.pyc", line 208, in _speak
  File "synthDrivers\jtalk\jtalkDriver.pyc", line 185, in _espeak_speak
NameError: name 'unicode' is not defined

```

**Comment by nishimotz** [comment]
jpalpha_191117j で解決していることを確認しました。
