### ISSUE TITLE
appveyor ビルドのエラー

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#238]
下記から発生

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/28948920

```
$errorCode=0
$outDir = (Resolve-Path .\testOutput\unit\)
$unitTestsXml = "$outDir\unitTests.xml"
py -m nose -sv --with-xunit --xunit-file="$unitTestsXml" ./tests/unit
if($LastExitCode -ne 0) { $errorCode=$LastExitCode }
Push-AppveyorArtifact $unitTestsXml
$wc = New-Object 'System.Net.WebClient'
$wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $unitTestsXml)
if($errorCode -ne 0) { $host.SetShouldExit($errorCode) }
py : test_boundingRectFromOffsetAtBottom (tests.unit.contentRecog.test_contentRecog.TestLinesWordsResult) ... ok
At line:4 char:1
+ py -m nose -sv --with-xunit --xunit-file="$unitTestsXml" ./tests/unit
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (test_boundingRe...sResult) ... ok:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
test_boundingRectFromOffsetAtLine2Start (tests.unit.contentRecog.test_contentRecog.TestLinesWordsResult) ... 
ok
```

中略

```
Output:  C:\projects\nvdajp\testOutput\system\output.xml
XUnit:   C:\projects\nvdajp\testOutput\system\systemTests.xml
Log:     C:\projects\nvdajp\testOutput\system\log.html
Report:  C:\projects\nvdajp\testOutput\system\report.html
Uploading artifact systemTestResult.zip (162,372 bytes)...100%
jptools\tests.cmd
The command line is too long.
scons: *** Error 1
scons: *** [output\nvda_jpalpha_191119h.pot] RuntimeError : xgettext failed
Traceback (most recent call last):
  File "C:\projects\nvdajp\include\scons\src\engine\SCons\Action.py", line 1202, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\projects\nvdajp\SConstruct", line 399, in makePot
    raise RuntimeError("xgettext failed")
RuntimeError: xgettext failed
error 2
Command exited with code -1
```

真っ赤なのは unittest だが、よく読むと xgettext で失敗している

**Comment by nishimotz** [comment]
ひとつ前の（成功した）ビルド

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/28930792

unittest のエラーはすでに出ている。

The command line is too long. が出ていなかった。どうやら本当の問題はこれか。

**Comment by nishimotz** [comment]
jptools/tests.cmd を一部コメントアウトしたらビルドが成功した。
