### ISSUE TITLE
SAPI4 ドライバーでのエラー

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#240]
本家版では起きていないが日本語アルファ版の最近のバージョンで、
本家 sapi4 ドライバーのリファクタリングの影響によるエラーが出ている。

```
ERROR - comtypes._comobject.call_with_this (19:18:55.160) - MainThread (15432):
Exception in ITTSBufNotifySink.TextDataDone implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 76, in call_with_this
  File "synthDrivers\sapi4.pyc", line 40, in ITTSBufNotifySink_TextDataDone
AttributeError: 'SynthDriverBufSink' object has no attribute '_synthDriver'
```

**Comment by nishimotz** [comment]
ブランチ alphajp と betajp にて修正。
