### ISSUE TITLE
ソースからnvdaを実行するとModuleNotFoundErrorが発生する

### ISSUE THREAD

**Issue by moutend** [nvdajp/nvdajp#257]
### システム構成

OSはWindows 10 Home 64 bit バージョン 1909 (OS ビルド 18363.592) です。

python関連の情報は以下の通りです。

```console
> py -3-32
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

>pip --version
pip 19.2.3 from c:\users\koyanagi\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

> scons --version
SCons by Steven Knight et al.:
        script: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 20
19-08-08 14:50:06, by bdeegan on octodog
        engine: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 20
19-08-08 14:50:06, by bdeegan on octodog
        engine path: ['c:\\users\\koyanagi\\appdata\\local\\program
s\\python\\python37\\lib\\site-packages\\scons\\SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
```

### 問題の再現手順

最新のalphajpブランチで`source\nvda.pyw`を実行するとModuleNotFoundErrorが発生します。再現手順は以下の通りです。

```console
git clone --recursive https://github.com/nvdajp/nvdajp
cd nvdajp
scons source
cd source
nvda.pyw -f debug.txt
```

### 実際に起きること

nvda.pywを実行すると、直後にエラーが発生した時の効果音が再生されます。しかし、画面上にはエラーメッセージは表示されません。

出力されるdebug.txtの内容は以下の通りです。

```
INFO - __main__ (09:54:11.577) - MainThread (6824):
Starting NVDA version source-run-source-d5c8fa7
INFO - __main__ (09:54:11.577) - MainThread (6824):
CRITICAL - __main__ (09:54:11.626) - MainThread (6824):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 216, in <module>
    import core
  File "core.py", line 31, in <module>
    import nvwave
  File "nvwave.py", line 15, in <module>
    import wx
  File "C:\Users\koyanagi\github.com\moutend\nvdajp\include\wxPython\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Users\koyanagi\github.com\moutend\nvdajp\include\wxPython\wx\core.py", line 12, in <module>
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'
```

上記のエラーメッセージの通り、`_core`に対応するファイルは存在しないようです。

(`include/wxPython/wx/_core.cp37-win32.pyd`は存在します)

### 期待されること

ソースからnvdaを実行できるようにしたいです。エラー解消のアドバイスいただけると助かります。

ところで本件とは直接関係ありませんが、`jptools/readme.md`にはビルドの手順が詳しく説明されています。同様にソースから実行する手順についても説明を追加していただけると助かります。

**Comment by nishimotz** [comment]
cd source
せずに
py -3-32 source\nvda.pyw
を実行するとどうなりますか？

複数のバージョンの Python がインストールされている環境だと、
拡張子 pyw がどの Python に関連付けられているかわからないので、
Python インタプリタを指定して実行するほうが安全です。

**Comment by moutend** [comment]
@nishimotz `py -3-32 source\nvda.pyw`を実行したところ、エラーが解消されました。`nvda.pyw`を直接実行すると自動的に適切なインタプリタが選ばれるのかと勘違いしていました。

補足になりますが、起動中のNVDAが終了し、ようこそ画面が読み上げられました。起動時の効果音も再生されたので、ソースからの実行に成功したようです。

迅速な回答ありがとうございました :+1:
