### ISSUE TITLE
Excel 2019の「検索と置換」ダイアログでのカーソル移動において、一部の漢字が詳細読みされない、または無音になる

### ISSUE THREAD

**Issue by Hasegawa-Hayate** [nvdajp/nvdajp#262]
### 問題の再現手順

1. Excel 2019を起動し、任意のブックを開く。
2. ctrl+fを押して、「検索と置換」ダイアログを開く。
3. tab/shift+tabで、「検索する文字列」のエディットにフォーカスする。
4. 「北赤羽駅長」と入力する。
5. カーソルを左端に戻してから1文字ずつ右に移動させ、入力した文字を読み上げさせる。この時、文字の読み上げが「説明モード」になっていること。

### 実際に起きること

カーソルを動かすごとに、「ホウガクノキタ、アカ、はね、テツドウノエキ」と読み上げ、最後の1文字は無音になってしまう。

詳細読みされる漢字、詳細読みされない漢字、無音になってしまう漢字に分かれる。

### 期待されること

カーソルを動かすごとに、「ホウガクノキタ、アカイノセキ、ハネノウ、テツドウノエキ、ナガイノチョウ」とすべての漢字が詳細読みされる。

### システム構成

NVDA 2019.3.1jp インストール環境(JTalk、tohoku-f01)

Windows 10 バージョン 1903 (OS ビルド 18362.720)(６４ビット版、日本語)

Microsoft Office 2019

### その他の質問

PC を再起動してもこの問題は再発する。

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 2019.2.1jp、及び、2020.1jp-beta-200323qでも再現する。

#### アドオンを無効化するとこの問題は解決しますか？

いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

いいえ

**Comment by nishimotz** [comment]
私の Excel 365 で再現しました。

ログに以下の記録がありました。

```
INFO - __main__ (15:58:38.422) - MainThread (31092):
Starting NVDA version jpalpha_200328l
INFO - core.main (15:58:39.101) - MainThread (31092):
Config dir: C:\Users\nishimotz\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (15:58:39.101) - MainThread (31092):
Loading config: C:\Users\nishimotz\AppData\Roaming\nvda\nvda.ini
INFO - core.main (15:58:39.284) - MainThread (31092):
Using Windows version 10.0.18363 workstation
INFO - core.main (15:58:39.285) - MainThread (31092):
Using Python version 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
INFO - core.main (15:58:39.285) - MainThread (31092):
Using comtypes version 1.1.7
INFO - core.main (15:58:39.285) - MainThread (31092):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (15:58:41.304) - MainThread (31092):
Loaded synthDriver kctalker
INFO - core.main (15:58:41.304) - MainThread (31092):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (15:58:41.317) - MainThread (31092):
Braille input initialized
INFO - braille.initialize (15:58:41.317) - MainThread (31092):
Using liblouis version 3.12.0
INFO - braille.initialize (15:58:41.322) - MainThread (31092):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (15:58:41.328) - MainThread (31092):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (15:58:41.665) - MainThread (31092):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (15:58:41.686) - _UIAHandler.UIAHandler.MTAThread (1092):
UIAutomation: IUIAutomation6
INFO - core.main (15:58:42.610) - MainThread (31092):
NVDA initialized
ERROR - eventHandler.executeEvent (15:58:52.854) - MainThread (31092):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x09CCA8D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1159, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (15:58:52.876) - MainThread (31092):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x09CCA8D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1159, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (15:58:52.892) - MainThread (31092):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x09CCA8D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1159, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (15:58:52.894) - MainThread (31092):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x09CCA8D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1159, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
```

**Comment by nishimotz** [comment]
本家 2020.1 beta1 で同じことをやったら、
「北赤羽駅長」と入力している途中でエラー音が出て、
下記のログを取得できた。

英語環境での再現手順を確認して、本家に報告する文章を作ります。

```
INFO - __main__ (17:50:13.935) - MainThread (27068):
Starting NVDA version 2020.1beta1
INFO - core.main (17:50:14.421) - MainThread (27068):
Config dir: C:\Users\nishimotz\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (17:50:14.421) - MainThread (27068):
Loading config: C:\Users\nishimotz\AppData\Roaming\nvda\nvda.ini
INFO - core.main (17:50:14.527) - MainThread (27068):
Using Windows version 10.0.18363 workstation
INFO - core.main (17:50:14.527) - MainThread (27068):
Using Python version 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
INFO - core.main (17:50:14.527) - MainThread (27068):
Using comtypes version 1.1.7
INFO - core.main (17:50:14.527) - MainThread (27068):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (17:50:16.524) - MainThread (27068):
Loaded synthDriver kctalker
INFO - core.main (17:50:16.524) - MainThread (27068):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (17:50:16.526) - MainThread (27068):
Braille input initialized
INFO - braille.initialize (17:50:16.526) - MainThread (27068):
Using liblouis version 3.12.0
INFO - braille.initialize (17:50:16.529) - MainThread (27068):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (17:50:16.533) - MainThread (27068):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (17:50:16.861) - MainThread (27068):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (17:50:16.878) - _UIAHandler.UIAHandler.MTAThread (34340):
UIAutomation: IUIAutomation6
INFO - core.main (17:50:17.812) - MainThread (27068):
NVDA initialized
ERROR - eventHandler.executeEvent (17:50:49.387) - MainThread (27068):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x0BDEDBB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (17:50:49.447) - MainThread (27068):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x0BDEDBB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (17:50:49.732) - MainThread (27068):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x0BDEDBB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (17:50:49.817) - MainThread (27068):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x0BDEDBB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
```

**Comment by nishimotz** [comment]
英語環境で確認して、本家にバグ報告を書きました。

https://github.com/nvaccess/nvda/issues/10936

**Comment by nishimotz** [comment]
あまり調査の時間を取れていなくてすみません。

過去にこの問題が起きていなくて、
どこかのバージョンから起きるようになった、
ということであれば、その原因になった変更を詳しく調べることができます。

今回は、この現象が起こらないバージョンの NVDA を
まだ見つけることができていません。
ですので、現在の 2020.1 の開発状況からすると、
修正されるのは 2020.2 以降になる可能性が高いです。

なにか補足していただける情報があればお知らせください。
