### ISSUE TITLE
ソースからのビルドでテストが失敗する

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#27]
AppVeyor ではテストでエラーが出ない

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/build/jpbeta-168

ローカルの場合

```
> jptools\nonCertAllBuild.cmd

...

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\unittest\__main__.py", line 12, in <module>
    main(module=None)
  File "C:\Python27\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "C:\Python27\lib\unittest\main.py", line 113, in parseArgs
    self._do_discovery(argv[2:])
  File "C:\Python27\lib\unittest\main.py", line 214, in _do_discovery
    self.test = loader.discover(start_dir, pattern, top_level_dir)
  File "C:\Python27\lib\unittest\loader.py", line 192, in discover
    __import__(start_dir)
  File "C:\work\nvda\nvdajp\tests\unit\__init__.py", line 64, in <module>
    import appModuleHandler
  File "C:\work\nvda\nvdajp\source\appModuleHandler.py", line 27, in <module>
    import NVDAHelper
  File "C:\work\nvda\nvdajp\source\NVDAHelper.py", line 12, in <module>
    import eventHandler
  File "C:\work\nvda\nvdajp\source\eventHandler.py", line 9, in <module>
    import api
  File "C:\work\nvda\nvdajp\source\api.py", line 18, in <module>
    import NVDAObjects.IAccessible
  File "C:\work\nvda\nvdajp\source\NVDAObjects\IAccessible\__init__.py", line 18, in <module>
    import IAccessibleHandler
  File "C:\work\nvda\nvdajp\source\IAccessibleHandler.py", line 312, in <module>
    IA2_STATE_PINNED:controlTypes.STATE_PINNED,
NameError: name 'IA2_STATE_PINNED' is not defined
scons: *** [tests\unit] Error 1
nvdajp build error 2
```

環境構築の不備かも知れないが jptools/readme.txt に反映させたいので記録しておく。

OneCore Voice 対応でツールチェーンの依存状況がちょっと変わっていることと関係があるのか、ないのか。

**Comment by nishimotz** [comment]
関係ありそうな過去のチケット
https://osdn.net/ticket/browse.php?group_id=4221&tid=32181

**Comment by nishimotz** [comment]
scons -c して scons すればビルドできることがわかった。
