### ISSUE TITLE
2022.1 本家版のマージ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#315]
本家 master ブランチを alphajp ブランチにマージしたらビルドが通らなくなった。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/41854202

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/41854203

```
Traceback (most recent call last):
  File "setup.py", line 291, in <module>
    + getRecursiveDataFiles('documentation', '../user_docs', excludes=('*.t2t', '*.t2tconf', '*/developerGuide.*'))
  File "C:\projects\nvdajp-q4r95\.venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python37\lib\distutils\core.py", line 148, in setup

  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1246, in _get_spec
TypeError: 'int' object is not iterable
scons: *** [dist] Error 1
Deactivating NVDA Python virtual environment
```

**Comment by nishimotz** [comment]
ローカル環境で再現できそう。

jptools/readme.md を更新しています。

https://github.com/nvdajp/nvdajp/commit/55eab0ec252e5ea138d8f76e396d2a590114efb2

**Comment by nishimotz** [comment]
状況が変わっていない
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42518158

**Comment by nishimotz** [comment]
現在 appveyor nvdajp 
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp
では alphajp のビルドをキャンセルしています。

nvdajp-noncert
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95
ではビルドはできているようですがテストが通らないので、
テストをスキップして詳細を確認します。

調査中の状況
scons に release=1 を渡すと表題のエラーが出ることがある。
このオプションをはずすとインストーラーが nvda_snapshot_xxx.exe という名前になり、
その後の処理が成功しない。
launcher に _snapshot という名前を付与しないような改変を一時的に行っている。

**Comment by nishimotz** [comment]
nvda_jpalpha_220212k_noncert.exe

ビルドは通ったけどいろいろエラーが出て動作が不完全な状況

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42547160/artifacts

```
ERROR - mouseHandler.initialize (10:57:42.511) - MainThread (9552):
Error retrieving initial mouse object
Traceback (most recent call last):
  File "mouseHandler.pyc", line 238, in initialize
  File "NVDAObjects\__init__.pyc", line 290, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 230, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 230, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 225, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 396, in getPossibleAPIClasses
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\UIA\__init__.pyc", line 2001, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 2002, in InputFlyout
AttributeError: module 'controlTypes' has no attribute 'ROLE_WINDOW'
ERROR - stderr (10:57:42.534) - Dummy-4 (16396):
--- Logging error ---

```

**Comment by nishimotz** [comment]
ローカル作業マシンで jptools\nonCertAllBuild.cmd して launcher を実行しても、
前述のエラーが出ないで動作している。
ビルド環境に依存するのか CI スクリプトの微妙な不備なのか。

**Comment by nishimotz** [comment]
ビルド中にこれが出るのがおかしいかも

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42547679

```
[00:14:04] cd source && C:\projects\nvdajp-q4r95\.venv\Scripts\python.exe -bb setup.py -vv build --build-base C:\projects\nvdajp-q4r95\build py2exe --dist-dir C:\projects\nvdajp-q4r95\dist
[00:14:04] running build
[00:14:04] running py2exe
[00:14:10] 
[00:14:10]   57 missing Modules                 
[00:14:10]   ------------------                 
[00:14:10] ? Carbon.Appearance                   imported from wx.lib.agw.aui.aui_utilities, wx.lib.agw.aui.tabart, wx.lib.colourutils
[00:14:10] ? Queue                               imported from synthDrivers.jtalk._bgthread, synthDrivers.jtalk.jtalkDriver
[00:14:10] ? StringIO                            imported from six
[00:14:10] ? UIA.UIA                             imported from NVDAObjects.IAccessible.sysTreeView32
[00:14:10] ? _1EA4DBF0_3C3B_11CF_810C_00AA00389B71_0_1_1 imported from comInterfaces.Accessibility
[00:14:10] ? _32F66A90_7614_11D4_BD11_00104BD3F987_0_1_0 imported from comInterfaces.MathPlayer
[00:14:10] ? _8CC497C9_A1DF_11CE_8098_00AA0047BE5D_0_1_0 imported from comInterfaces.tom
[00:14:10] ? _944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0 imported from comInterfaces.UIAutomationClient
[00:14:10] ? _A6245497_9C0B_4449_85A5_BD6AD07DF8EA_0_0_0 imported from comInterfaces.ISimpleDOM
[00:14:10] ? _C523F390_9C83_11D3_9094_00104BD0D535_0_3_0 imported from comInterfaces.AcrobatAccessLib
[00:14:10] ? _C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4 imported from comInterfaces.SpeechLib
[00:14:10] ? _CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3 imported from comInterfaces.IAccessible2Lib
[00:14:10] ? __builtin__                         imported from wx.py.sliceshell
[00:14:10] ? __main__                            imported from bdb, pdb, rlcompleter, wx.py.filling, wx.py.shell, wx.py.sliceshell
[00:14:10] ? _frozen_importlib                   imported from importlib, importlib.abc
[00:14:10] ? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc
[00:14:10] ? _nvdajp_spellchar                   imported from synthDrivers.jtalk.mecab
[00:14:10] ? _nvdajp_unicode                     imported from synthDrivers.jtalk._nvdajp_espeak, synthDrivers.jtalk.roma2kana, synthDrivers.jtalk.translator2
[00:14:10] ? _uuid                               imported from uuid
[00:14:10] ? _winreg                             imported from brailleDisplayDrivers.brailleMemo, brailleDisplayDrivers.kgs, platform
[00:14:10] ? collections.Mapping                 imported from configobj
[00:14:10] ? compiler                            imported from configobj
[00:14:10] ? comtypes.gen.AcrobatAccessLib       imported from NVDAObjects.IAccessible.adobeAcrobat
[00:14:10] ? comtypes.gen.IAccessible2Lib        imported from virtualBuffers.gecko_ia2
[00:14:10] ? comtypes.gen.ISimpleDOM             imported from NVDAObjects.IAccessible.ia2Web
[00:14:10] ? comtypes.gen.MathPlayer             imported from mathPres.mathPlayer
[00:14:10] ? comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0 imported from comInterfaces._1EA4DBF0_3C3B_11CF_810C_00AA00389B71_0_1_1, comInterfaces._32F66A90_7614_11D4_BD11_00104BD3F987_0_1_0, comInterfaces._8CC497C9_A1DF_11CE_8098_00AA0047BE5D_0_1_0, comInterfaces._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0, comInterfaces._C523F390_9C83_11D3_9094_00104BD0D535_0_3_0, comInterfaces._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4, comInterfaces._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3, comInterfaces.stdole
[00:14:10] ? comtypes.gen._1EA4DBF0_3C3B_11CF_810C_00AA00389B71_0_1_1 imported from comInterfaces.Accessibility, comInterfaces._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3
[00:14:10] ? comtypes.gen._32F66A90_7614_11D4_BD11_00104BD3F987_0_1_0 imported from comInterfaces.MathPlayer
[00:14:10] ? comtypes.gen._8CC497C9_A1DF_11CE_8098_00AA0047BE5D_0_1_0 imported from comInterfaces.tom
[00:14:10] ? comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0 imported from comInterfaces.UIAutomationClient
[00:14:10] ? comtypes.gen._A6245497_9C0B_4449_85A5_BD6AD07DF8EA_0_0_0 imported from comInterfaces.ISimpleDOM
[00:14:10] ? comtypes.gen._C523F390_9C83_11D3_9094_00104BD0D535_0_3_0 imported from comInterfaces.AcrobatAccessLib
[00:14:10] ? comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4 imported from comInterfaces.SpeechLib
[00:14:10] ? comtypes.gen._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3 imported from comInterfaces.IAccessible2Lib
[00:14:10] ? java.lang                           imported from platform
[00:14:10] ? jtalkDir                            imported from synthDrivers.jtalk.jtalkDriver, synthDrivers.jtalk.translator2
[00:14:10] ? mecab                               imported from synthDrivers.jtalk.jtalkCore, synthDrivers.jtalk.translator2
[00:14:10] ? netradiorecorder4                   imported from appModules.netradiorecorder5, appModules.netradiorecorder6, appModules.netradiorecorder7, appModules.netradiorecorder8
[00:14:10] ? numpy.ctypeslib                     imported from comtypes.npsupport
[00:14:10] ? org.python.core                     imported from copy, pickle
[00:14:10] ? os.path                             imported from addonHandler, brailleInput, ctypes._aix, nvwave, os, pkgutil, py_compile, sysconfig, tracemalloc, unittest, unittest.util
[00:14:10] ? readline                            imported from cmd, code, pdb, rlcompleter
[00:14:10] ? roma2kana                           imported from synthDrivers.jtalk.mecab
[00:14:10] ? sets                                imported from comtypes.tools.codegenerator, comtypes.tools.tlbparser, comtypes.tools.typedesc_base
[00:14:10] ? speech.CharacterModeCommand         imported from synthDrivers.jtalk._nvdajp_espeak, synthDrivers.nvdajp_jtalk
[00:14:10] ? speech.IndexCommand                 imported from synthDrivers.nvdajp_jtalk
[00:14:10] ? speech.LANGS_WITH_CONJUNCT_CHARS    imported from jpUtils, speech
[00:14:10] ? speech.LangChangeCommand            imported from synthDrivers.nvdajp_jtalk
[00:14:10] ? speech.PitchCommand                 imported from synthDrivers.nvdajp_jtalk
[00:14:10] ? speech.SpeechCommand                imported from synthDrivers.nvdajp_jtalk
[00:14:10] ? speech.getCharDescListFromText      imported from jpUtils, speech
[00:14:10] ? speech.getCurrentLanguage           imported from jpUtils, speech
[00:14:10] ? speech.speakTextInfo                imported from documentBase, speech
[00:14:10] ? text2mecab                          imported from synthDrivers.jtalk.mecab
[00:14:10] ? translator1                         imported from synthDrivers.jtalk.translator2
[00:14:10] ? window.Window                       imported from NVDAObjects.IAccessible.MSHTML, NVDAObjects.IAccessible.sysListView32, NVDAObjects.JAB, NVDAObjects.UIA.winConsoleUIA
[00:14:10] 
```

**Comment by nishimotz** [comment]
betajp ブランチの noncert ビルド
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42547200

```
  40 missing Modules                 
  ------------------
```

と出ているが、ビルドは問題なく動く。

**Comment by nishimotz** [comment]
現在は alphajp と betajp の py2exe のバージョンの違いを疑っている。
py2exe 0.11.0.1 が nvdajp に固有のソースコードをうまくスキャンできていない？

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42548243/artifacts
nvda_jpalpha_220212p_noncert.exe

https://github.com/nvdajp/nvdajp/issues/315#issuecomment-1036941360 と同じような不完全な実行ファイルだった

**Comment by nishimotz** [comment]
やったこと

* alphajp からバージョン表記や jptools の更新を betajp に取り込んだ
* ここまでの alphajp を alphajp-220212 ブランチとして残した
* 現時点の betajp からブランチを切り直して alphajp を作り直し GitHub の alphajp を強制上書きした

確認できていること

* betajp ブランチは AppVeyor では正しくビルドできてシステムテストも通っている
* betajp ブランチを私のローカル開発環境でビルドすると不完全なバイナリができることがあり、作業が不確実

今後の方針

* betajp から実験ブランチを切って本家 2022.1 の変更内容をすこしずつ取り込んで AppVeyor 実験ビルドを試す
* 例えば py2exe の更新だけやってみる
* いずれ alphajp に本家 master をマージする運用に戻すが、これも最初は実験ブランチを切って行う
* ビルドに問題ないかどうかの判断は AppVeyor ビルドで行う
* ビルド方法やスクリプトを、なるべく本家版に揃えていく

**Comment by nishimotz** [comment]
本家版 NVDA version alpha-25008,c8d96591 で

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42955057/artifacts

の nvdajp-jtalk-220320v.nvda-addon が問題なく動作している。

**Comment by nishimotz** [comment]
alphajp-220212 に本家 master を merge して AppVeyor ビルドに再挑戦する。
本家で py2exe 関連の更新がいろいろ行われたので、こちらの問題が解決した可能性がある。

**Comment by nishimotz** [comment]
署名なしビルドは成功している
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/42960249/artifacts

署名ありビルドは signtool verify で失敗している。
スキップしたらどうなるか試している。

**Comment by nishimotz** [comment]
署名なしビルドで出ているエラー。確かに直す必要がありそう

```
INFO - __main__ (18:06:41.409) - MainThread (13200):
Starting NVDA version jpalpha_220321q_noncert
INFO - core.main (18:06:41.479) - MainThread (13200):
Config dir: C:\Users\nishimotz\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (18:06:41.479) - MainThread (13200):
Loading config: C:\Users\nishimotz\AppData\Roaming\nvda\nvda.ini
INFO - core.main (18:06:41.529) - MainThread (13200):
Windows version: Windows 11 21H2 (10.0.22000) workstation
INFO - core.main (18:06:41.529) - MainThread (13200):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (18:06:41.529) - MainThread (13200):
Using comtypes version 1.1.8
INFO - core.main (18:06:41.529) - MainThread (13200):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (18:06:42.322) - MainThread (13200):
Loaded synthDriver kctalker
WARNING - mathPres.initialize (18:06:42.332) - MainThread (13200):
MathPlayer 4 not available
INFO - core.main (18:06:42.332) - MainThread (13200):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (18:06:42.334) - MainThread (13200):
Braille input initialized
INFO - braille.initialize (18:06:42.335) - MainThread (13200):
Using liblouis version 3.21.0
INFO - braille.initialize (18:06:42.337) - MainThread (13200):
Using pySerial version 3.5
INFO - braille.BrailleHandler.setDisplayByName (18:06:42.343) - MainThread (13200):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (18:06:42.619) - MainThread (13200):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (18:06:42.679) - UIAHandler.UIAHandler.MTAThread (16292):
UIAutomation: IUIAutomation6
INFO - NVDAHelperLocal (18:06:42.839) - UIAHandler.UIAHandler.MTAThread (16292):
Thread 16292, build\x86\UIARemote\UIARemote.cpp, initialize, 145:
Registered C:\Users\nishimotz\AppData\Local\Temp\nstEED5.tmp\app\lib\jpalpha_220321q_noncert\Microsoft.UI.UIAutomation.dll.manifest

INFO - NVDAHelperLocal (18:06:42.849) - UIAHandler.UIAHandler.MTAThread (16292):
Thread 16292, build\x86\UIARemote\UIARemote.cpp, initialize, 150:
Microsoft.UI.UIAutomation is available

ERROR - mouseHandler.initialize (18:06:42.869) - MainThread (13200):
Error retrieving initial mouse object
Traceback (most recent call last):
  File "mouseHandler.pyc", line 238, in initialize
  File "NVDAObjects\__init__.pyc", line 287, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 227, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 227, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 222, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 407, in getPossibleAPIClasses
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\UIA\__init__.pyc", line 2002, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 2003, in InputFlyout
AttributeError: module 'controlTypes' has no attribute 'ROLE_WINDOW'
INFO - core.main (18:06:43.054) - MainThread (13200):
NVDA initialized
ERROR - core.CorePump.run (18:06:43.109) - MainThread (13200):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 742, in run
  File "IAccessibleHandler\__init__.pyc", line 1071, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 649, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 576, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 70, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 71, in __call__
  File "NVDAObjects\__init__.pyc", line 222, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 407, in getPossibleAPIClasses
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "NVDAObjects\UIA\__init__.pyc", line 2002, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 2003, in InputFlyout
AttributeError: module 'controlTypes' has no attribute 'ROLE_WINDOW'
```

**Comment by nishimotz** [comment]
30分で打ち切るように設定していたら、時間切れで failed になった模様
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/42961324/messages

**Comment by nishimotz** [comment]
いろいろスキップしたらやっとビルドが通った

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/42971365/artifacts

**Comment by nishimotz** [comment]
signtool verify のログ

```
File: dist\lib\jpalpha_220322j\IAccessible2proxy.dll
Index  Algorithm  Timestamp    
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\IAccessible2proxy.dll

File: dist\lib\jpalpha_220322j\ISimpleDOM.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\ISimpleDOM.dll

File: dist\lib\jpalpha_220322j\Microsoft.UI.UIAutomation.dll
Index==Algorithm==Timestamp====
========================================
File: dist\lib\jpalpha_220322j\nvdaHelperLocal.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\nvdaHelperLocal.dll

File: dist\lib\jpalpha_220322j\nvdaHelperLocalWin10.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\nvdaHelperLocalWin10.dll

File: dist\lib\jpalpha_220322j\nvdaHelperRemote.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\nvdaHelperRemote.dll

File: dist\lib\jpalpha_220322j\UIARemote.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\UIARemote.dll

File: dist\lib\jpalpha_220322j\windowsaccessbridge-32.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib\jpalpha_220322j\windowsaccessbridge-32.dll


Number of files successfully Verified: 7

Number of errors: 1

File: dist\lib64\jpalpha_220322j\IAccessible2proxy.dll
Index  Algorithm  Timestamp    
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib64\jpalpha_220322j\IAccessible2proxy.dll

File: dist\lib64\jpalpha_220322j\ISimpleDOM.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib64\jpalpha_220322j\ISimpleDOM.dll

File: dist\lib64\jpalpha_220322j\nvdaHelperRemote.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\lib64\jpalpha_220322j\nvdaHelperRemote.dll

File: dist\libArm64\jpalpha_220322j\IAccessible2proxy.dll
Index  Algorithm  Timestamp    
========================================
0      sha256     RFC3161      

Successfully verified: dist\libArm64\jpalpha_220322j\IAccessible2proxy.dll

File: dist\libArm64\jpalpha_220322j\ISimpleDOM.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\libArm64\jpalpha_220322j\ISimpleDOM.dll

File: dist\libArm64\jpalpha_220322j\nvdaHelperRemote.dll
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\libArm64\jpalpha_220322j\nvdaHelperRemote.dll

File: dist\nvda_dmp.exe
Index  Algorithm  Timestamp    
========================================
0      sha256     RFC3161      

Successfully verified: dist\nvda_dmp.exe

File: dist\nvda_eoaProxy.exe
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\nvda_eoaProxy.exe

File: dist\nvda_noUIAccess.exe
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\nvda_noUIAccess.exe

File: dist\nvda_slave.exe
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\nvda_slave.exe

File: dist\nvda_uiAccess.exe
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\nvda_uiAccess.exe

File: dist\uninstall.exe
Index==Algorithm==Timestamp====
========================================
0      sha256     RFC3161      

Successfully verified: dist\uninstall.exe

File: output\nvda_jpalpha_220322j.exe
Index  Algorithm  Timestamp    
========================================
0      sha256     RFC3161      

Successfully verified: output\nvda_jpalpha_220322j.exe

```

**Comment by nishimotz** [comment]
日本語アルファ版の更新
nvda_jpalpha_220322j を自動更新の対象としてデプロイしました。
API バージョン 2022.1 に移行するので、非互換のプラグインは無効化されます。

**Comment by nishimotz** [comment]
またテストが通らなくなった
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/43001480

**Comment by nishimotz** [comment]
ビルドが安定して通るようになった alphajp-220212 を `git push --force-with-lease origin alphajp` で強制上書きした。

以前の alphajp は alphajp-220316 としていちおう残した。

**Comment by nishimotz** [comment]
本家 beta ブランチを betajp ブランチにマージして、ビルドとテストが通るようになった。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/43108075

betajp ブランチから alphajp ブランチに衝突せずマージできる状態に戻った。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/43108328
