### ISSUE TITLE
braillememo experimentalで起動できない

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajp#339]
### 問題の再現手順

1. 設定→点字で点字ディスプレイドライバ「Braillememo Experimental」を選ぶ。
2. NVDAを再起動する.
3. 点字が表示されない。

### 実際に起きること

点字が表示されないでNVDAは「点字なし」で起動する

### 期待されること

「Braillememo Experimental」ドライバでてんじが表示できる。

### システム構成

Microsoft Windows
バージョン 21H2 (OS ビルド 19044.1645)

NonVisual Desktop Access (NVDA)
Version: jpalpha_220717s

**Comment by nishimotz** [comment]
Windows 11 + NVDA 2022.2jp + USB シリアルケーブル + BM46 で確認した状況

```
INFO - brailleDisplayDrivers.brailleMemo.BrailleDisplayDriver.__init__ (15:16:26.145) - MainThread (10568):
failed COM4
ERROR - braille.BrailleHandler.setDisplayByName (15:16:26.145) - MainThread (10568):
Error initializing display driver brailleMemo for kwargs {'port': 'COM4'}
Traceback (most recent call last):
  File "braille.pyc", line 1980, in setDisplayByName
  File "brailleDisplayDrivers\brailleMemo.pyc", line 362, in __init__
RuntimeError: No KGS display found
INFO - braille.BrailleHandler.setDisplayByName (15:16:26.145) - MainThread (10568):
Loaded braille display driver noBraille, current display has 0 cells.
```

**Comment by nishimotz** [comment]
こちらでは下記の回避策が有効でした。

(1)
%appdata%\nvda\nvda.ini をエディタで開き、
display を brailleMemo に書きかえる。

```
[braille]
	display = brailleMemo
```

(2)
この状態で NVDA を起動する。

補足すると

* kgs = デフォルトの KGS ドライバー
* brailleMemo = experimental ドライバー

kgs から brailleMemo への切り替えに失敗していると思います。
自動選択で kgs ドライバーが選択できなかったときには、
この問題の影響を受けにくかったのでは。

いったん「点字なし」にしてから、
あらためて braille memo experimental を選び直す、
というワークアラウンドもありえますね。。

もうすこし調べてみます。

**Comment by nishimotz** [comment]
やはり以下の回避策も有効と思います。

(1)
点字ディスプレイを「自動設定」からいったん「点字なし」にする。

(2)
NVDA を再起動して、あらためて braille memo experimental を選び直す。

**Comment by ma10** [comment]
この件、2022.3jp利用時、BMS40がBluetooth接続されている環境で確認したところ、「ポート」が「自動設定」になっているとエラーが発生するようです。（2022.1までは問題なかったのですが。）

エラー発生時のログは以下の通りです：

`````
INFO - brailleDisplayDrivers.brailleMemo.BrailleDisplayDriver.terminate (15:00:29.812) - MainThread (9784):
KGS driver terminating
INFO - brailleDisplayDrivers.brailleMemo.BrailleDisplayDriver.terminate (15:00:35.716) - MainThread (9784):
KGS driver terminated 1
ERROR - braille.BrailleHandler.setDisplayByName (15:00:35.744) - MainThread (9784):
Error initializing display driver brailleMemo for kwargs {'port': 'auto'}
Traceback (most recent call last):
  File "braille.pyc", line 2026, in setDisplayByName
  File "brailleDisplayDrivers\brailleMemo.pyc", line 362, in __init__
RuntimeError: No KGS display found
INFO - brailleDisplayDrivers.brailleMemo.BrailleDisplayDriver.terminate (15:00:35.745) - MainThread (9784):
KGS driver terminating
`````

明示的にポートを指定した場合は問題なさそうです。
