### ISSUE TITLE
u+fffd の文字が点字ディスプレイに表示されない

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#342]
[nvdajp-team:00081] でご報告いただいた内容です。

Thunderbirdでメールを閲覧していますと、特定のメールでメールのタイトルも本文も点字ディスプレイに表示されないことがあります。
音声では正常に読み上げています。
デバッグログを取りますと下記のようなエラーが出力されていました。

OS:Windows 10 Home 64ビット 21H2
NVDAのバージョン:2022.2JP
点字ディスプレイ:KGS ブレイルメモスマート40

以下、ログは一部伏せ字にしています。

```
----
ERROR - eventHandler.executeEvent (17:55:24.970) - MainThread (9112):
error executing event: gainFocus on <NVDAObjects.Dynamic_RowWithFakeNavigationMozillaIAccessible object at 0x0FE2DDD0> with extra args of {}
Traceback (most recent call last):
   File "eventHandler.pyc", line 285, in executeEvent
   File "eventHandler.pyc", line 99, in __init__
   File "eventHandler.pyc", line 108, in next
   File "C:\Users\*****\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 465, in event_gainFocus
     nextHandler()
   File "eventHandler.pyc", line 108, in next
   File "appModules\thunderbird.pyc", line 28, in event_gainFocus
   File "eventHandler.pyc", line 108, in next
   File "NVDAObjects\__init__.pyc", line 1160, in event_gainFocus
   File "braille.pyc", line 2160, in handleGainFocus
   File "braille.pyc", line 2165, in _doNewObject
   File "braille.pyc", line 1814, in getFocusRegions
   File "braille.pyc", line 806, in update
   File "braille.pyc", line 536, in update
   File "louisHelper.pyc", line 69, in translate
   File "synthDrivers\jtalk\translator2.pyc", line 1794, in translate
   File "synthDrivers\jtalk\translator2.pyc", line 1736, in translateWithInPos2
   File "synthDrivers\jtalk\translator2.pyc", line 1616, in japanese_braille_separate
IndexError: string index out of range
DEBUG - gui.settingsDialogs.SettingsDialog._setInstanceDestroyedState (17:55:24.975) - MainThread (9112):
Setting state to destroyed for instance: NVDAの設定 - NVDASettingsDialog - <gui.settingsDialogs.NVDASettingsDialog object at 0x0CD6A490>
Current _instances ['NVDAの設定 - CREATED']
IO - inputCore.InputManager.executeGesture (17:55:27.186) - winInputHook (20056):
Input: kb(desktop):upArrow
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (17:55:27.232) - MainThread (9112):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (17:55:27.232) - MainThread (9112):
----
```

**Comment by nishimotz** [comment]
```
該当のメールのタイトルには「�（\ufffd）」という文字列が含まれているようです。
```
とのこと

**Comment by nishimotz** [comment]
メモ帳に u+fffd を貼り付けて点字ビューアーで確認して、下記のログを得ました

```
DEBUG - louisHelper.translate (18:22:16.553) - MainThread (12316):
  
DEBUG - synthDrivers.jtalk.mecab.Mecab_print (18:22:16.556) - MainThread (12316):
0  ,記号,一般,*,*,*,*,*
1 　,記号,空白,*,*,*,*,　,　,　,*/*,*

ERROR - eventHandler.executeEvent (18:22:16.557) - MainThread (12316):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIAWindowNVDAObject object at 0x06A0CFF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 285, in executeEvent
  File "eventHandler.pyc", line 99, in __init__
  File "eventHandler.pyc", line 108, in next
  File "NVDAObjects\behaviors.pyc", line 242, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1270, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1160, in event_gainFocus
  File "braille.pyc", line 2160, in handleGainFocus
  File "braille.pyc", line 2165, in _doNewObject
  File "braille.pyc", line 1817, in getFocusRegions
  File "braille.pyc", line 1280, in update
  File "braille.pyc", line 536, in update
  File "louisHelper.pyc", line 69, in translate
  File "synthDrivers\jtalk\translator2.pyc", line 1794, in translate
  File "synthDrivers\jtalk\translator2.pyc", line 1736, in translateWithInPos2
  File "synthDrivers\jtalk\translator2.pyc", line 1616, in japanese_braille_separate
IndexError: string index out of range
```

**Comment by nishimotz** [comment]
下記で再現した

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajpmiscdep/builds/44462733

```
======================================================================
ERROR: test_pass2 (__main__.JpBrailleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 17, in test_pass2
    count, outfile = jpBrailleRunner.pass2()
  File "C:\projects\nvdajpmiscdep\jptools\jpBrailleRunner.py", line 140, in pass2
    t["text"], logwrite=__print, nabcc=nabcc
  File "C:\projects\nvdajpmiscdep\source\synthDrivers\jtalk\translator2.py", line 1736, in translateWithInPos2
    outbuf, inpos2 = japanese_braille_separate(inbuf, logwrite, nabcc=nabcc)
  File "C:\projects\nvdajpmiscdep\source\synthDrivers\jtalk\translator2.py", line 1616, in japanese_braille_separate
    if mo.nhyouki[0] == "[" and mo.nhyouki[-1] == "]":
IndexError: string index out of range
----------------------------------------------------------------------
Ran 5 tests in 13.642s
```

**Comment by nishimotz** [comment]
u+fffd を ? として出力するようにしました。

![image](https://user-images.githubusercontent.com/76300/184538410-76183b4a-a44b-4032-adc4-6674868fba50.png)
