### ISSUE TITLE
NVDA 2022.2jp のネットラジオレコーダー8対応

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#343]
[nvda-japanese-users:3280] にてご指摘いただいている件をこちらでカバーします。

NVDA 2022.2jp で動作していないが、ナレーターでは動作している、とのことです。

過去の作業
#124

こちらではネットラジオレコーダー7までは実際に動作確認をしていますが、
2018.4jp 以降メンテナンスされていません。

**Comment by nishimotz** [comment]
「陸の部屋」のアドオンについて前述の過去チケットで書きましたが、
現在は公開されていないようです。

**Comment by nishimotz** [comment]
2022.2jp-beta-220717s + ネットラジオレコーダー7 で下記のエラーを確認しました。

```
ERROR - core.CorePump.run (18:02:09.277) - MainThread (14704):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 742, in run
  File "IAccessibleHandler\__init__.pyc", line 1057, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 868, in processForegroundWinEvent
  File "appModuleHandler.pyc", line 277, in update
  File "appModuleHandler.pyc", line 262, in getAppModuleFromProcessID
  File "appModuleHandler.pyc", line 242, in getAppNameFromProcessID
  File "appModuleHandler.pyc", line 209, in _importAppModuleForExecutable
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "appModules\netradiorecorder7.pyc", line 5, in <module>
ModuleNotFoundError: No module named 'netradiorecorder4'
```

**Comment by nishimotz** [comment]
下記でネットラジオレコーダー7が従来通りに動作することを確認しました。
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/44438733/artifacts

**Comment by riku22** [comment]
>「陸の部屋」のアドオンについて前述の過去チケットで書きましたが、
>現在は公開されていないようです。

すみません、新しいアドオンに移行したのですが、リダイレクト漏れしていますね。
過去チケットで紹介されていたアドオンは、 [rikuAppModules] に統合されています。

[rikuAppModules]: https://riku22.net/soft/rikuAppModules
