### ISSUE TITLE
本家 2023.1 から日本語版へのマージ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#366]
beta -> alphajp にマージして衝突した箇所

* tsf.cpp : C++ モダナイズ
* braille.py : たぶんテーブルの見出しの独自対応。いったん本家 beta をそのまま取り込む
* globalCommands.py : レビューで左右の文字移動、フォーカスの読み上げなどで文字説明をする拡張。いったん本家 beta をそのまま取り込む。
* configSpec / 起動画面 : 無変換、変換、Esc を NVDA キーとする設定はいままでの nvda.ini の値をそのまま使う

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/46175409

```
tsf.cpp
build\x86\remote\tsf.cpp(679): error C2065: 'jpAttrLen': undeclared identifier
scons: *** [build\x86\remote\tsf.obj] Error 2
Deactivating NVDA Python virtual environment
Command exited with code 2
```

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/46199113/tests

* ビルドは通った
* テストがたくさん落ちている。robot が全滅だが、system も一部落ちている

**Comment by nishimotz** [comment]
テストが通ってないバイナリをダウンロードして作業環境で実行。気づいたこと

* デスクトップ配列のテンキー2を4回押しても「読みかたモード」「説明モード」の切り替えが動いていない
* Windows+R のダイアログの「参照」で NVDA+Tab を2回押すと「参 照」のような文字単位の説明
* レビューで左右の文字移動は特にリグレッションしてない気がする

**Comment by nishimotz** [comment]
読みかたモードの操作で出ているエラー

```
IO - inputCore.InputManager.executeGesture (17:09:11.204) - winInputHook (17856):
Input: kb(laptop):NVDA+.
ERROR - scriptHandler.executeScript (17:09:11.234) - MainThread (21264):
error executing script: <bound method GlobalCommands.script_review_currentCharacter of <globalCommands.GlobalCommands object at 0x09CDBC30>> with gesture 'NVDA+.'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "globalCommands.pyc", line 1880, in script_review_currentCharacter
UnboundLocalError: local variable 'characterDescriptionMode' referenced before assignment
```

**Comment by nishimotz** [comment]
global 文がマージミスで消えていたので修正

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/46204066/tests

tests.unit.test_braille.TestFocusContextPresentation.test_fillDisplay
nosetests
16 ms

```
Traceback (most recent call last):
  File "C:\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python37\lib\unittest\case.py", line 624, in run
    self.setUp()
  File "C:\projects\nvdajp\tests\unit\test_braille.py", line 33, in setUp
    braille.handler.handleGainFocus(self.obj)
  File "C:\projects\nvdajp\source\braille.py", line 2474, in handleGainFocus
    self._doNewObject(itertools.chain(getFocusContextRegions(obj, oldFocusRegions=self.mainBuffer.regions), getFocusRegions(obj)))
  File "C:\projects\nvdajp\source\braille.py", line 2479, in _doNewObject
    for region in regions:
  File "C:\projects\nvdajp\source\braille.py", line 1937, in getFocusContextRegions
    region.update()
  File "C:\projects\nvdajp\source\braille.py", line 854, in update
    columnHeaderText=columnHeaderText,
NameError: name 'columnHeaderText' is not defined
```

**Comment by nishimotz** [comment]
WinMerge で3つ見比べて、削りすぎたと思われる箇所を発見

* 本家 beta
* alphajp
* betajp

**Comment by nishimotz** [comment]
Robot.chromeTests はどれも下記のエラーで落ちている
```
Error message:
Speech did not finish before timeout
```

**Comment by nishimotz** [comment]
NVDA+Tab を2回押したときの挙動を日本語版の仕様に戻す。

**Comment by nishimotz** [comment]
日本語アルファ版を jpalpha_230211u に更新。

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/46357423/tests
Robot.symbolPronunciationTests.symbolInSpeechUI が通らないのでスキップするか。。

**Comment by nishimotz** [comment]
前述の作業を行ったので、本件を完了とします。
