### ISSUE TITLE
テーブルの行・列読み上げコマンドの不具合

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#372]
### 問題の再現手順

1. Chromeを開く
2. https://gmail.com を開く
3. メールリストでブラウズモードにする
4. "ctrl+alt+nvda+カーソルキー" のコマンドを実行する

### 実際に起きること

押したカーソルキーの方向にある1つのセルの内容を読み上げる。
場合によっては以降"ctrl+alt+カーソルキー" のテーブル内移動コマンドが動作しなくなる。(NVDAの再起動で元に戻る)

### 期待されること

カーソルキーを押した方向の列や行の内容を順番に読み上げる。
"nvda+ctrl+alt+カーソルキー"の順で押した場合は期待した読み上げが行われる。

### システム構成

NVDA 日本語版 Version: 2023.1jp-beta-230323j (2023.1.0.1983) インストール環境

Windows 11 ホーム バージョン 22H2 (OS ビルド 22621.1413) 日本語環境

Chrome バージョン: 111.0.5563.111（Official Build） （64 ビット）

#### PC を再起動してもこの問題は再発しますか？

はい

#### アドオンを無効化するとこの問題は解決しますか？

いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

いいえ

**Comment by nishimotz** [comment]
ご報告ありがとうございます。
本家版からのマージで失敗してるかもしれないですね。
問題が起きたときに nvda.log にエラーが出ていますか？
（ログは私信でもかまわないです）

**Comment by yama3nomori** [comment]
下記のようなログが出力されていました。

## nvda.log の内容

ERROR - scriptHandler.executeScript (17:14:45.714) - MainThread (4956):
error executing script: <bound method DocumentWithTableNavigation.script_nextColumn of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x03C61E70>> with gesture 'オルト+コントロール+右矢印'
Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 559, in _getTableCellAt
AttributeError: 'IAccessible' object has no attribute 'IAccessibleTable2Object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "documentBase.pyc", line 480, in script_nextColumn
  File "documentBase.pyc", line 417, in _tableMovementScriptHelper
  File "documentBase.pyc", line 362, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 577, in _getNearestTableCell
  File "documentBase.pyc", line 278, in _getNearestTableCell
  File "virtualBuffers\gecko_ia2.pyc", line 561, in _getTableCellAt
AttributeError: 'IAccessible' object has no attribute 'IAccessibleTableObject'

**Comment by nishimotz** [comment]
それらしい現象は再現しましたが、
高負荷で装飾キーの処理がおかしくなる挙動に近いですね。
Gmail のテーブルはセルの文字数が多くて、処理が追い付かないことがありそうですね。
Gmail 以外でも起きますか？

**Comment by yama3nomori** [comment]
エクセルでも同様の減少を確認しています。
ただ、どちらのケースでもnvdaキーから順番にコマンドを押した場合はエラーにはなっていません。

**Comment by yama3nomori** [comment]
NVDAのコマンド一覧でも発生しています。

**Comment by nishimotz** [comment]
2023.2 で性能改善が入る見込みなので、
本家 master をマージしたビルドを作ってみました。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/46683650/artifacts

nvda_jpalpha_230403s.exe

こちらで試した限りでは、キー入力の取りこぼしが減ったような感じがします。

**Comment by yama3nomori** [comment]
早速ありがとうございます。

試してみました。

コマンドの成功率は上がっているようです。

また失敗したとしてもテーブルの閲覧コマンドが壊れることがなくなったようです。


ctrl+alt+nvda を同時に押したときは動作することもあるのですが、

ctrlから順番に押して行って実行した場合はエラーになっています。

以下ログの内容です。



## nvda.log の内容


INFO - synthDriverHandler.setSynth (11:27:18.667) - MainThread (12580):

Loaded synthDriver oneCore
WARNING - mathPres.initialize (11:27:18.705) - MainThread (12580):
MathPlayer 4 not available
INFO - core.main (11:27:18.705) - MainThread (12580):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (11:27:18.705) - MainThread (12580):
Braille input initialized
INFO - braille.initialize (11:27:18.705) - MainThread (12580):
Using liblouis version 3.25.0
INFO - braille.initialize (11:27:18.705) - MainThread (12580):
Using pySerial version 3.5
INFO - braille.BrailleHandler._setDisplay (11:27:18.721) - MainThread 
(12580):
Loaded braille display driver 'noBraille', current display has 0 cells.
INFO - core.main (11:27:19.695) - MainThread (12580):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (11:27:19.915) - 
UIAHandler.UIAHandler.MTAThread (15112):
UIAutomation: IUIAutomation6
INFO - NVDAHelperLocal (11:27:20.338) - UIAHandler.UIAHandler.MTAThread 
(15112):
Thread 15112, build\x86\UIARemote\UIARemote.cpp, initialize, 145:
Registered 
C:\nvda_alpha\lib\jpalpha_230403s\Microsoft.UI.UIAutomation.dll.manifest

INFO - NVDAHelperLocal (11:27:20.386) - UIAHandler.UIAHandler.MTAThread 
(15112):
Thread 15112, build\x86\UIARemote\UIARemote.cpp, initialize, 150:
Microsoft.UI.UIAutomation is available

INFO - core.main (11:27:20.480) - MainThread (12580):
NVDA initialized
WARNING - synthDrivers.oneCore._OcSsmlConverter.convertLangChangeCommand 
(11:27:25.695) - MainThread (12580):
Language en not supported ({'ja_jp'})
ERROR - queueHandler.flushQueue (11:27:26.029) - MainThread (12580):
Error in func _TextReader.nextLine
Traceback (most recent call last):
   File "queueHandler.pyc", line 64, in flushQueue
   File "speech\sayAll.pyc", line 269, in nextLine
   File "speech\sayAll.pyc", line 223, in nextLineImpl
   File "textInfos\offsets.pyc", line 619, in move
   File "virtualBuffers\__init__.pyc", line 228, in _getStoryLength
OSError: [WinError 1775] リモート プロシージャ 
コール中にクライアントからホストに NULL コンテキスト 
ハンドルが渡されました。
