### ISSUE TITLE
本家 2023.2 から日本語版へのマージ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#383]
nvaccess master から alphajp へのマージで、tests.unit.test_brailleDisplayDrivers.TestGestureMap.test_identifiers が落ちた。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/47251419/tests

**Comment by nishimotz** [comment]
ID_PARTS_REGEX を直そうかと思ったが、本家のテストが通っているので、もうすこし確認する。
いったん unittest.skip する。

**Comment by nishimotz** [comment]
test_moveCaret_never_moveReviewAndActivate あたりが通らない

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/47524268/tests

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/47649464/artifacts

本家 beta1 相当のはずだが、実行するとエラーが出て OneCore がまともに動かない

```
ERROR - eventHandler.executeEvent (17:24:16.697) - MainThread (9524):
error executing event: gainFocus on <NVDAObjects.IAccessible.MenuItem object at 0x0A02A170> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 130, in setFocusObject
AttributeError: 'NoneType' object has no attribute 'name'
```
