### ISSUE TITLE
ビルド手順の再整備

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#389]
新しいビルドサーバーに関する作業をこちらに記録します。

**Comment by nishimotz** [comment]
```
jptools\tests.cmd
......E.........................
======================================================================
ERROR: test_getDiscriminantReading (__main__.JpUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\projects\nvdajp-shuaruta-5qc0041768sw882n\jptools\mocks\logHandler\log.py", line 11, in debug
    print('DEBUG %s' % s)
UnicodeEncodeError: 'cp932' codec can't encode character '\u2b55' in position 7: illegal multibyte sequence
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "jpDicTest.py", line 148, in test_getDiscriminantReading
    saycap = jpUtils.getDiscriminantReading(source, sayCapForCapitals=True)
  File "..\source\jpUtils.py", line 336, in getDiscriminantReading
    log.debug("(%s) %d %s" % (uc, len(c), getAttrDesc(ca)))
  File "C:\Users\appveyor\projects\nvdajp-shuaruta-5qc0041768sw882n\jptools\mocks\logHandler\log.py", line 13, in debug
    print('DEBUG %r' % s)
UnicodeEncodeError: 'cp932' codec can't encode character '\u2b55' in position 8: illegal multibyte sequence
```

**Comment by nishimotz** [comment]
現状

* BYOC でまず署名なしビルドして artifacts を取得できることを目指している
* betajp ブランチで作業をしていたが、不必要なビルドを回したくないので方針変更
* shuaruta ブランチを作成し appveyor-jp-shuaruta.yml を参照している
* scons が最後まで実行されるとジョブが終わらず、タイムアウトで失敗する症状。ときどき成功するが、安定しない
* scons のターゲットを絞ってすこしずつ検証する作業中

**Comment by nishimotz** [comment]
現状

* AppVeyor BYOC 現在ためしている機材では署名なしビルドすらまともに動かない

**Comment by nishimotz** [comment]
AppVeyor にこだわるのをやめて、作業マシンでリリースビルドできることを目指す。

```
rmdir /s/q nvdajp
git clone --depth 1 -b shuaruta --recursive https://github.com/nvdajp/nvdajp.git
cd nvdajp
call jptools\certLocalBuild.cmd
cd ..
```

**Comment by nishimotz** [comment]
releasejp ブランチ = 2023.1jp をローカル環境で署名ビルドできている。

```
rmdir /s/q nvdajp
git clone --depth 1 -b releasejp --recursive https://github.com/nvdajp/nvdajp.git
cd nvdajp
copy c:\work\shuaruta\pfx\shuaruta-key-pass-2022.txt jptools\secret
copy c:\work\shuaruta\pfx\shuaruta-key220824.pfx jptools\secret
set RELEASE=1
set VERSION=2023.1jp
set UPDATEVERSIONTYPE=nvdajp
set PUBLISHER=nvdajp
call venvUtils\venvCmd.bat jptools\certAllBuild.cmd version_build=9999
cd ..
```

betajp や alphajp ブランチだとビルドが途中で止まる。

#376 作業に問題がありそう。

**Comment by nishimotz** [comment]
shu-releasejp branch

* 2023.1jp を新しいコード証明書で私の作業マシンでビルド
* 過去の仕様：certFile 指定がない場合は証明書なしビルド
* このブランチの仕様：certTimestampServer 指定がない場合は証明書なしビルド

**Comment by nishimotz** [comment]
もうすぐ不要になるが2022年の証明書で起きた問題

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/47859289

SignTool Error: No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option. 
The system cannot find the path specified.
nvdajp build error 1
Command exited with code -1

下記で解決

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/47859454

signtool のバージョンを上げたことが原因だった：

https://github.com/nvdajp/nvdajp/commit/768d4acb87138909ce0d2fa072a08ccbb2ce5bce

現状 shu-releasejp ブランチは、AppVeyor でも署名ビルドができており、私の作業マシンでは
jptools/certBuild2023.cmd
でビルドが通る。

作業環境にはコードサイニング証明書 2023 秘密鍵を格納したUSBデバイスを接続しておく。

ビルドの途中で、証明書管理ツールのパスワード入力画面が出るので、対応する。

これは証明書管理ツールを設定すれば Windows を再起動するまでパスワード不要になる。

**Comment by nishimotz** [comment]
appveyor プロジェクトの nvdajp-noncert を削除しました。

**Comment by nishimotz** [comment]
version_build.txt に初期値を入れて、下記 build.cmd をコマンドプロンプトで実行できている。

なぜか PowerShell に移植すると buildVersion.py でエラーになって止まる。

```
setlocal enabledelayedexpansion
set /p VERSION_BUILD=<version_build.txt
set BRANCH=releasejp
rmdir /s/q %BRANCH%-%VERSION_BUILD%
git clone --depth 1 -b %BRANCH% --recursive https://github.com/nvdajp/nvdajp.git %BRANCH%-%VERSION_BUILD%
cd %BRANCH%-%VERSION_BUILD%
set RELEASE=1
set VERSION=2023.1jp
set UPDATEVERSIONTYPE=nvdajp
set PUBLISHER=nvdajp
call venvUtils\venvCmd.bat jptools\certBuild2023.cmd version_build=%VERSION_BUILD%
cd ..
set value=%VERSION_BUILD%
set /a value+=1
echo %value% > version_build.txt
```

**Comment by nishimotz** [comment]
証明書 2022 が無効になり、AppVeyor で証明書ビルドできなくなりました。

**Comment by nishimotz** [comment]
日本語アルファ版と日本語ベータ版が、非公開のビルド環境でコード署名を行ったバージョンに移行しました。
