### ISSUE TITLE
2023.3 に向けた KGS ドライバー作業

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#393]
master を alphajp にマージするにあたり、いったん KGS ドライバーの自動検出を削除している。

下記が本家 alva の変更例

```
class BrailleDisplayDriver(braille.BrailleDisplayDriver, ScriptableObject): 
	supportsAutomaticDetection = True 
 
	@classmethod 
	def registerAutomaticDetection(cls, driverRegistrar: bdDetect.DriverRegistrar): 
		driverRegistrar.addUsbDevices(bdDetect.KEY_HID, { 
			"VID_0798&PID_0640",  # BC640 
			"VID_0798&PID_0680",  # BC680 
			"VID_0798&PID_0699",  # USB protocol converter 
		}) 
 
		driverRegistrar.addBluetoothDevices(lambda m: m.id.startswith("ALVA ")) 
 
```

**Comment by nishimotz** [comment]
changes

- Added official support to register custom braille display drivers in the automatic braille display detection process.
Consult the ``braille.BrailleDisplayDriver`` class documentation for more details.
Most notably, the ``supportsAutomaticDetection`` attribute must be set to ``True`` and the ``registerAutomaticDetection`` ``classmethod`` must be implemented.  (#15196)

- ``bdDetect.addUsbDevices`` and ``bdDetect.addBluetoothDevices`` have been deprecated.
Braille display drivers should implement the ``registerAutomaticDetection`` classmethod instead.
That method receives a ``DriverRegistrar`` object on which the ``addUsbDevices`` and ``addBluetoothDevices`` methods can be used. (#15200)

**Comment by nishimotz** [comment]
nvda_install.log

```
CRITICAL - __main__ (22:10:07.692) - MainThread (6448):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 549, in main
  File "bdDetect.pyc", line 575, in initialize
  File "brailleDisplayDrivers\kgs.pyc", line 329, in registerAutomaticDetection
TypeError: addUsbDevices() takes 3 positional arguments but 4 were given
DEBUG - easeOfAccess.isRegistered (22:10:07.692) - MainThread (6448):
Unable to find AT registry key
```
