### ISSUE TITLE
本家 master から alphajp へのマージ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#424]
下記まではちゃんと動いている

* 9c52492b0188b79e07c4ce09b09d42478b0c33b2
* https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/48468140

その後行ったマージでこうなっている

* appveyor のテストが通らない
* ビルドマシンで作ったバイナリが正常に起動しない（起動音が2回鳴って、すでにインストールされているNVDAが起動してしまう）

**Comment by nishimotz** [comment]
```
CRITICAL - __main__ (16:59:39.909) - MainThread (7036):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 622, in main
  File "gui\__init__.pyc", line 783, in initialize
  File "gui\__init__.pyc", line 149, in __init__
  File "gui\__init__.pyc", line 592, in __init__
  File "gui\__init__.pyc", line 703, in _appendHelpSubMenu
AttributeError: 'SysTrayIcon' object has no attribute 'docsMenu'
DEBUG - easeOfAccess.isRegistered (16:59:39.909) - MainThread (7036):
Unable to find AT registry key
```

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/48490403/artifacts

**Comment by nishimotz** [comment]
```
CRITICAL - __main__ (22:32:24.191) - MainThread (20144):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 622, in main
  File "gui\__init__.pyc", line 783, in initialize
  File "gui\__init__.pyc", line 149, in __init__
  File "gui\__init__.pyc", line 592, in __init__
  File "gui\__init__.pyc", line 718, in _appendHelpSubMenu
NameError: name 'menu_help' is not defined

```

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/48492960

リリース用ビルドも正常に戻りました。

**Comment by nishimotz** [comment]
本家masterでcontrollerClientのリファクタリングが行われたが、
alphajp では、それ以前から artifacts に DLL が入ってない状況が起きている。

**Comment by nishimotz** [comment]
点字ビューアーでエラーが出ている

```
ERROR - unhandled exception (10:46:21.008) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.583) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.672) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.693) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.732) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.780) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.828) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.859) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.905) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.951) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:24.983) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
ERROR - unhandled exception (10:46:31.598) - MainThread (27864):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
  File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
  File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
  File "brailleViewer\brailleViewerGui.pyc", line 103, in update
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
```

**Comment by nishimotz** [comment]
https://github.com/nvdajp/nvdajp/commit/91358967f54c8b8c3221b3301934e96875ec5672

にて下記が解決

> 点字ビューアーでエラーが出ている
> 
> ```
> ERROR - unhandled exception (10:46:21.008) - MainThread (27864):
> Traceback (most recent call last):
>   File "brailleViewer\brailleViewerGui.pyc", line 321, in <lambda>
>   File "brailleViewer\brailleViewerGui.pyc", line 513, in _updateGui
>   File "brailleViewer\brailleViewerGui.pyc", line 192, in updateControls
>   File "brailleViewer\brailleViewerGui.pyc", line 103, in update
> TypeError: Colour(): arguments did not match any overloaded call:
>   overload 1: too many arguments
>   overload 2: argument 1 has unexpected type 'float'
>   overload 3: argument 1 has unexpected type 'float'
>   overload 4: argument 1 has unexpected type 'float'
> ```
