### ISSUE TITLE
AppVeyor 2024.1jp

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#425]
Set-WinSystemLocale ja-JP 前後の処理で動かなくなった。

これらの処理をいったん外してみた。つまり en-US 環境の Windows でビルドする。

https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/48602656

出てきたエラーと警告

```
C:\projects\nvdajp\miscDepsJp\include\jtalk\make_jdic.py:127: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  + datetime.utcnow().strftime("%Y%m%d-%H%M%S")

C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\translator2.py:452: SyntaxWarning: invalid escape sequence '\,'
  "^[\,\.\:\;\!\?\@\#\\\$\%\&\*\|\+\-\/\=\<\>\"'\^\`\_\~]+$"
C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\translator2.py:1247: SyntaxWarning: invalid escape sequence '\-'
  RE_MB_ALPHA_NUM_SPACE = re.compile("^[0-9A-Za-z\- ０-９Ａ-Ｚａ-ｚ　]+$")
C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\translator2.py:1248: SyntaxWarning: invalid escape sequence '\.'
  RE_ASCII_CHARS = re.compile("^[A-Za-z0-9\.\,\-\+\:\/\~\?\&\%\#\*\$\; ]+$")
C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\translator2.py:1249: SyntaxWarning: invalid escape sequence '\+'
  RE_INFORMATION = re.compile("^[A-Za-z0-9\+\@\/\#\$\%\&\*\;\.\<\>\-\_\{\}\[\] ]+$")
C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\translator2.py:1250: SyntaxWarning: invalid escape sequence '\,'
  RE_GAIJI = re.compile("^[A-Za-z][A-Za-z0-9\,\.\+\-'\!\? ]+$")
C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\text2mecab.py:49: SyntaxWarning: invalid escape sequence '\?'
  [re.compile("\?"), "？"],
...E.
======================================================================
RROR: test_jtalk (__main__.JtalkTests.test_jtalk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\nvdajp\miscDepsJp\jptools\test.py", line 37, in test_jtalk
    ret = jtalkRunner.main(do_play=False, do_write=False, do_log=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\nvdajp\miscDepsJp\jptools\jtalkRunner.py", line 202, in main
    libjt_initialize(JT_DLL)
  File "C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\jtalkCore.py", line 273, in libjt_initialize
    libjt = cdll.LoadLibrary(JT_DLL)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ctypes\__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\projects\nvdajp\miscDepsJp\source\synthDrivers\jtalk\libopenjtalk.dll' (or one of its dependencies). Try using the full path with constructor syntax.
----------------------------------------------------------------------
Ran 5 tests in 13.747s
FAILED (errors=1)
```

**Comment by nishimotz** [comment]
やったこと

* AppVeyor を再起動せずに英語環境のままビルドを通す
* mecab 関連のコンパイルで CL にオプションを渡してエラーを回避
