### ISSUE TITLE
SAPI4 ProTALKER が動いていない

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#428]
### 問題の再現手順

SAPI4でProTALKERが使える環境でNVDAを起動し、音声設定でSAPI4を選択する。

### 実際に起きること

音声が出ない。

### 期待されること

音声が出る。

### システム構成

1. NVDA バージョン: 2024.1jp-beta-231213i
2. Windows バージョン: Windows 11 23H2 (10.0.22631) workstation AMD64

2023.3jp では期待通りに動作している。

下記はログ出力

```
Speaking ['NVDAの設定: 音声 (通常の設定)', 'ダイアログ', CancellableSpeech (still valid)]
ERROR - eventHandler.executeEvent (20:00:13.087) - MainThread (29160):
error executing event: gainFocus on <NVDAObjects.Dynamic_NvdaDialogEmptyDescriptionNvdaDialogDialogIAccessibleWindowNVDAObject object at 0x05406E90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "appModules\nvda.pyc", line 211, in event_gainFocus
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 700, in speakObject
  File "speech\speech.pyc", line 1051, in speak
  File "speech\manager.pyc", line 265, in speak
  File "speech\manager.pyc", line 425, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 200, in speak
UnboundLocalError: cannot access local variable 'isPitchCommand' where it is not associated with a value
```

**Comment by nishimotz** [comment]
本家 alpha-30253 (2024.1系) では ProTALKER が動いている。

**Comment by nishimotz** [comment]
本家 alpha の最新版 30306 (2024.2系) でも SAPI4 問題なし。

**Comment by nishimotz** [comment]
本家のリファクタリングのマージに失敗していた可能性。
修正をビルド中。

**Comment by nishimotz** [comment]
2024.1jp-beta-231215j で修正しました。
