### ISSUE TITLE
Microsoft IME 候補ウィンドウ表示でログにエラーが出る

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#469]
日本語変換の第1候補を確定せず、スペースキーを押して第2候補に移動したときに表示される。

```
ERROR - core.CorePump.Notify (00:29:50.440) - MainThread (10444):
AutoPropertyObject.invalidateCaches failed
Traceback (most recent call last):
  File "core.pyc", line 885, in Notify
  File "baseObject.pyc", line 182, in invalidateCaches
AttributeError: 'Dynamic_' object has no attribute 'invalidateCache'
ERROR - core.CorePump.Notify (00:29:51.456) - MainThread (10444):
AutoPropertyObject.invalidateCaches failed
```

調べていると `AttributeError: 'Dynamic_' object has no attribute` のパターンがいくつか再現できて、
https://github.com/nvdajp/nvdajp/issues/374 にも関係がありそう。

**Comment by nishimotz** [comment]
本家版での検証をしていませんが、単純に AttributeError を回避する修正を行います。
