### ISSUE TITLE
サロゲートペアへの対応と絵文字辞書

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#7]
https://osdn.jp/ticket/browse.php?group_id=4221&tid=30841

**Comment by nishimotz** [comment]
https://osdn.jp/ticket/browse.php?group_id=4221&tid=36402

**Comment by nishimotz** [comment]
Windows7 SP1 32bit + Firefox 47.0 で下記のエラーという報告。

```
ERROR - eventHandler.executeEvent (21:04:55):
error executing event: gainFocus on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x04D24470> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 143, in executeEvent
  File "eventHandler.pyo", line 91, in __init__
  File "eventHandler.pyo", line 98, in next
  File "appModules\firefox.pyo", line 24, in event_stateChange
  File "eventHandler.pyo", line 98, in next
  File "browseMode.pyo", line 1283, in event_gainFocus
  File "textInfos\offsets.pyo", line 362, in expand
  File "virtualBuffers\__init__.pyo", line 314, in _getUnitOffsets
  File "textInfos\offsets.pyo", line 344, in _getUnitOffsets
  File "textInfos\offsets.pyo", line 226, in _getCharacterOffsets
  File "textInfos\offsets.pyo", line 195, in _getStoryText
NotImplementedError
```
