### ISSUE TITLE
Windows 8.1 で SAPI5 がエラーになる

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#79]
Windows 8.1 で SAPI5 がエラーになるという報告をメールでいただきました。

まだ現象を再現できていませんが、わかったことがあればこちらで報告します。

### 問題

エラーメッセージ：
音声エンジンエラー。音声エンジン Sapi5 を読み込めません。
となる。

### システム構成

OS: Windows 8.1 64bit pro
NVDA: 2018.1.1 JP

### ログの内容

```
INFO - __main__ (15:04:00.651):
Starting NVDA
INFO - core.main (15:04:01.137):
Config dir: C:\Usersユーザー名\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (15:04:01.137):
Loading config: C:\Users\ユーザー名\AppData\Roaming\nvda\nvda.ini
INFO - core.main (15:04:01.351):
NVDA version 2018.1.1jp
INFO - core.main (15:04:01.352):
Using Windows version 6.3.9600 workstation
INFO - core.main (15:04:01.354):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (15:04:01.355):
Using comtypes version 1.1.3
INFO - synthDrivers.jtalk.mecab.Mecab_initialize (15:04:02.256):
dic: C:\Program Files (x86)\NVDA\synthDrivers\jtalk\dic
INFO - synthDrivers.jtalk.mecab.Mecab_initialize (15:04:02.256):
mecab:0.996 nvdajp-jtalk-dic (utf-8) 20180328-054646
INFO - synthDrivers.jtalk.jtalkDriver.initialize (15:04:02.365):
loaded C:\Program Files (x86)\NVDA\synthDrivers\jtalk\tohokuf01\tohoku-f01-neutral.htsvoice
INFO - synthDrivers.jtalk.jtalkDriver.initialize (15:04:02.506):
loaded C:\Program Files (x86)\NVDA\synthDrivers\jtalk\mei\mei_happy.htsvoice
INFO - synthDriverHandler.setSynth (15:04:02.522):
Loaded synthDriver nvdajp_jtalk
INFO - core.main (15:04:02.522):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (15:04:02.522):
Braille input initialized
INFO - braille.initialize (15:04:02.522):
Using liblouis version 3.3.0
INFO - braille.BrailleHandler.setDisplayByName (15:04:02.522):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (15:04:02.615):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (15:04:02.631):
UIAutomation: IUIAutomation3
INFO - core.main (15:04:03.069):
NVDA initialized
WARNING - stdout (15:04:28.710):
hooked waveOutOpen
WARNING - stdout (15:04:28.710):
hooked waveOutClose
WARNING - synthDriverHandler.SynthDriver.loadSettings (15:04:29.147):
Invalid voice: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_JA-JP_HARUKA_11.0
ERROR - synthDriverHandler.setSynth (15:04:29.147):
setSynth
Traceback (most recent call last):
  File "synthDriverHandler.pyo", line 91, in setSynth
  File "synthDriverHandler.pyo", line 500, in loadSettings
  File "synthDriverHandler.pyo", line 32, in changeVoice
  File "synthDrivers\sapi5.pyo", line 172, in _set_voice
  File "synthDrivers\sapi5.pyo", line 125, in _getVoiceTokens
COMError: (-2147200967, None, (None, None, None, 0, None))
INFO - synthDrivers.jtalk.jtalkDriver.initialize (15:04:29.335):
loaded C:\Program Files (x86)\NVDA\synthDrivers\jtalk\tohokuf01\tohoku-f01-neutral.htsvoice
INFO - synthDrivers.jtalk.jtalkDriver.initialize (15:04:29.460):
loaded C:\Program Files (x86)\NVDA\synthDrivers\jtalk\mei\mei_happy.htsvoice
INFO - synthDriverHandler.setSynth (15:04:29.474):
Loaded synthDriver nvdajp_jtalk
```

**Comment by nishimotz** [comment]
Windows 8.1 が2023年1月にサポート終了しているのでクローズします。
